### ISSUE TITLE
Readme and dependencies

### ISSUE THREAD

**Issue by Stefaans** [dbfannin/ngx-logger#1]
Thank you for this Angular 4 implementation of your logger!

I have encountered two issues that I managed to resolve:

1. Dependencies: Requires the moments package, which was not part of my project. Easy to fix by installing the moments packages, but should be specified as a package dependency.
2. Readme: Seems to be missing a providers statement:
`providers: [
        ....
        NGXLogger,
        ....
    ],`

Keep up the good work!

**Comment by dbfannin** [comment]
Thanks for the feedback! I've made suggested changes and pushed the changes up this morning.
