### ISSUE TITLE
warn/info/debug multiple arguments.

### ISSUE THREAD

**Issue by jimmymain** [dbfannin/ngx-logger#10]
Hi,

First off, thanks for enabling the dark theme. Sorted out my color issue.
The browser console.log accepts multiple arguments, which is useful for logging a message, and objects to the console.

Have you thought about allowing multiple arguments to the NGX-Logger.
Would you accept a pull request if I gave it a try or is it something you would consider doing?

Nice component - simple - does the job.

**Comment by dbfannin** [comment]
@jimmymain I have considered that, but just haven't really had the time recently. I would love for you to take on the task! Just send me a PR when you have something ready!

**Comment by leo6104** [comment]
In my fork project, there is two issue with supporting this feature. 
https://github.com/leo6104/ngx-logger/blob/master/src/logger.service.ts

1. IE not support rest parameter & spread operator ( ...args: any[]) 
2. To support this feature, enableDarkTheme cannot be supported. 

https://github.com/leo6104/ngx-logger/blob/master/src/logger.service.ts#L119 
console.log(`%c${moment.utc().format()} [${level}]`, `color:${color1}`, ...messages); 
There is no way to use spread operator with coloring. 
For object debugging strategy, object should be printed as object, not JSON.stringify string. 

Is there any way to solve this two issue?

**Comment by dbfannin** [comment]
@leo6104, thanks for taking a stab at solving this problem.  

1. For the first issue, this module is made to be used from the npm repo https://www.npmjs.com/package/ngx-logger. If you are using that, the typescript has been compiled down into JS and will be compatible for all browsers (including IE). This module is not meant to be used directly.

2. This can be solved programatically. There are a few different ways it can be done. One would be to build the message string prior to logging, then the spread operator would no longer be necessary.

Hopefully this gives some guidance. Thanks again for your interest in contributing.

**Comment by leo6104** [comment]
Thanks for your good guidance. 
1. I did tsc compile and i could understand it will be fine with any browser. Thank you for letting me know that when the spread operator is converted from typescript to javascript, it will be translated with considering browser compatibility. (I knew the wrong information.) 
2. Of course, message string would be able to coloring. But, If we support object as console.log(object), we can spread object in console.log like this. ![console.logging](https://i.imgur.com/ca26T20.png)

**Comment by dbfannin** [comment]
@leo6104, 

I see your point. In order to continue to support the dark them, we should not support objects as log message, but rather as additional data. We can have our meta information and the message colored as we have in the past, and spread out the additional parameters in the console.log. This way, we support dark theme, rest params, and object console logging. Seems like the best compromise to me.

Example (paste in console to see output):
console.log(`%ctimestamp [level] %cmessage`, `color:red`, `color:black`, {key: 'value'})

This means the logging functions would need to be extended like below (feel free to come up with better parameter naming)
error(message: string, ...additional: any[]) {
    
}

**Comment by leo6104** [comment]
@dbfannin I agree with you. I will try this issue. Please review PR later. :)

**Comment by dbfannin** [comment]
@leo6104, thanks for the PR today. Looks great. I've merged it and published version 0.2.3

Thanks for all the collaboration!
