### ISSUE TITLE
Problem in  npm install --save ngx-logger gives error

### ISSUE THREAD

**Issue by rkkp1023** [dbfannin/ngx-logger#100]
npm install --save ngx-logger
npm ERR! Unexpected end of JSON input while parsing near '...ODZ2t4/3Ydem+b2\nnpiu'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ravi/.npm/_logs/2018-12-07T06_30_35_865Z-debug.log

--------------------------------LOG FILE--------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'ngx-logger' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose npm-session 7e19d8f4d5d24195
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/ngx-logger 18ms (from cache)
8 silly fetchPackageMetaData error for ngx-logger@latest Unexpected end of JSON input while parsing near '...ODZ2t4/3Ydem+b2\nnpiu'
9 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ODZ2t4/3Ydem+b2\nnpiu'
9 verbose stack     at JSON.parse (<anonymous>)
9 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
9 verbose stack     at consumeBody.call.then.buffer (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
9 verbose stack     at <anonymous>
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
10 verbose cwd /home/ravi/Sample
11 verbose Linux 4.15.0-33-generic
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "ngx-logger"
13 verbose node v8.11.4
14 verbose npm  v5.6.0
15 error Unexpected end of JSON input while parsing near '...ODZ2t4/3Ydem+b2\nnpiu'
16 verbose exit [ 1, true ]

**Comment by dbfannin** [comment]
@rkkp1023, I don't believe this is an issue with ngx-logger. I verified this by running the install myself this morning. It is most likely that your package.json is not valid JSON. I would run your package.json file through a JSON validator. Good luck!
