### ISSUE TITLE
text colors on log messages

### ISSUE THREAD

**Issue by noririco** [dbfannin/ngx-logger#101]
console.log("%cSending...: ","color:red");
this.logger.debug("%cSending...: ","color:red");

In chrome devtools:
Sending...:   <-------- this shows in red
ngx-logger.js:256 2018-12-11T07:26:03.023Z DEBUG [main.js:3881] %cSending...:  color:red

anyway to overcome this and change the color ?

Thanks!

**Comment by dbfannin** [comment]
@noririco. NGX Logger is not built to be like console.log. It is a log management tool with a lot of features built on top of it. Custom colors as an input parameter in the log methods is not something we support, and probably will not build support for it in the future (unless we get a lot of requests for it).

If you need to have custom colors on your logs, see the *Custom Log Monitoring* section in the README. The custom log monitor allows you to capture all logs and handle them as you will.

I hope this helps!
