### ISSUE TITLE
How can i send my custom payload to the serving looging url?

### ISSUE THREAD

**Issue by parijatsharma93** [dbfannin/ngx-logger#107]
Hi,
Please tell me how can i send my custom payload to the serving logging url?Also When is the server logging Url called that is passed in the LoggerModule.forroot() ?I am unable to understand anything from the current Readme.md file
Also please can you provide a better README.MD file where you will show some examples of how we can use all the methods and fucntions you have provided.i Need to club it with ErrorHandling in my Project.Please please provide a solution @dbfannin

**Comment by dbfannin** [comment]
@parijatsharma93, sorry you were having trouble consuming the readme. If you would like to help improve it, I'd be more than happy to look over a PR with your changes.

You cannot send a custom payload to the backend using the built in server logging logic. The payload body is predefined and not customizable. If you wish to have more control over how the messages are logged, please look at the *Custom Log Monitoring* section of the readme.
