### ISSUE TITLE
Question: log customization

### ISSUE THREAD

**Issue by C0ZEN** [dbfannin/ngx-logger#115]
I would like to add more customization to the Logger when printing the logs.
I am opening this Issue to talk about all the possibilities before creating a pull request to make sure that you are seeing the benefits of them.

**List of potential features:**
- Enabled/disabled the visibility of the date
- Enabled/disabled the visibility of the file name
- Customize the date format [not-important]

If you agree on the need to add them, I would like to make it possible with a pull request.
Thanks.

**Comment by barocsi** [comment]
+1 this I thought this is evident. Also passing a custom log printing function during .create phase would be awesome.

**Comment by victorgutierrez** [comment]
Would it be possible to add to the log information about which browser the request is being made?

**Comment by C0ZEN** [comment]
I am very sorry but the struggle is real.  
From my point of view, there is so much to do before actually creating new features.  
The project is not even Angular 8 ready and I really do not want to do all the grunt work here so I will stop here.
