### ISSUE TITLE
Question: preferred companion backend 

### ISSUE THREAD

**Issue by gioid** [dbfannin/ngx-logger#119]
Hi,
do you recommend any backend project to store/manage remote logging?

**Comment by dbfannin** [comment]
@gioid, Thanks for your interest in using NGX Logger! The Logger is completely separate from the backend, so it will work with the backend of your choice. You just need to set up the appropriate HTTP Endpoint. Check out the docs for more info!

**Comment by jllodra** [comment]
I know this issue is quite old but I developed this very simple node endpoint that persists logs to a file.

https://github.com/atlantis-of-code/ngx-logger-backend

Just in case if it's of any help to anybody.
