### ISSUE TITLE
Add support for passing objects for output to console.

### ISSUE THREAD

**Issue by FieldMarshallVague** [dbfannin/ngx-logger#12]
Hi, good job on the logger, it's something that's sorely needed.

I just wanted to raise a request to add support for logging objects/vars as well as messages.  Myself and colleagues usually output a message with the object/array/var that's relevant to it, like so:

```
console.log("object was passed to component", myObj);
```

It let's us inspect the object in the debugger console, which we wouldn't get with a stringified version.

Obviously, at the moment, we couldn't do this with ngx-logger, but I'd like to recommend it as the standard approach going forward.  I don't have time to do a PR myself right now, but may after the project finishes in a couple of months.

**Comment by dbfannin** [comment]
I agree this would be a good enhancement. If I don't have an opportunity to get to it before you can, please feel free to make the changes and send me a PR.

Thanks!

**Comment by dbfannin** [comment]
the logger now supports logging objects as of 0.2.3. The consensus was to leave the message as a string to support coloring for users using the "darkTheme", but allow for additional parameters to be passed and logged to console. example:

`logger.error('message goes here', {data: 'More info here'})`

Thanks for the suggestion!

**Comment by FieldMarshallVague** [comment]
Awesome, dude!  Nice one :)
