### ISSUE TITLE
Custom payload for http logging

### ISSUE THREAD

**Issue by luislora** [dbfannin/ngx-logger#128]
Is there a way to make custom payload message, I’m getting bad request responses from my server, caused by the default format

**Comment by jia2015** [comment]
i want to know the answer too. Does anyone know how to use that CustomNGXLoggerService to create a custom payload?

**Comment by dbfannin** [comment]
Sorry for the late response here, but the correct way to do this would be to use a custom NGXLoggerMonitor. See the docs for more details!
