### ISSUE TITLE
File name is unkown when main.js is minified

### ISSUE THREAD

**Issue by cole-adams** [dbfannin/ngx-logger#129]
The new custom source map parsing works great on a dev build, but I'm finding when the main.js file is minified to be all on one line, the file name and line number are always 'unknown' and 0 respectively.

<img width="325" alt="sourceMap" src="https://user-images.githubusercontent.com/10216883/60897631-a8bda000-a225-11e9-8053-ad5f399bdeba.PNG">

<img width="325" alt="logMessage" src="https://user-images.githubusercontent.com/10216883/60897660-b115db00-a225-11e9-9fc0-7bdb5aa678cf.PNG">

**Comment by mcpierce** [comment]
Is there any work being done to address this issue?

**Comment by dbfannin** [comment]
Not actively as far as I'm aware. Would be more than happy to take a look at a PR if you want to take a stab at it.

**Comment by qortex** [comment]
Close here and follow-up in #187
