### ISSUE TITLE
400 bad request with the latest change of HttpClient -> HttpBackend

### ISSUE THREAD

**Issue by yankycranky** [dbfannin/ngx-logger#131]
Started getting 400 bad request for server-side logging, which was working earlier.

I was using custom http headers ( Required for Api key which can only be fed from server-side for security reasons), which was working fine with earlier versions but now it doesn't seem to work.

**Comment by ctaleck** [comment]
I believe the intent is that HttpBackend is used to by-pass interceptors so that there is more control during the logging process.  So if you need to inject http headers, you can do so specifically for logging using the Params object. Is that possible in your scenario?

**Comment by dbfannin** [comment]
In order to support your interceptors implement a custom NGXLoggerMonitor, to handle the HTTP request yourself. Thanks!
