### ISSUE TITLE
Avoiding dependency on HttpClient module

### ISSUE THREAD

**Issue by dsebastien** [dbfannin/ngx-logger#134]
Recently, I've updated ngx-logger from 3.x to 4.x. While doing so, I get injection errors because I didn't import the HttpClient module yet in my application.

Apparently since 4.x, that module MUST be loaded for ngx-logger to work. Is it possible to disable this behavior? Currently I don't need to do log shipping.

**Comment by gloriousjob** [comment]
Agreed. I actually avoided upgrading until I figured this out recently. At the very least, the following needs to be added to the installation documentation until this is resolved:

import { HttpClientModule } from '@angular/common/http';

imports: [
    BrowserModule,
    // import HttpClientModule after BrowserModule.
    HttpClientModule,
...
  ],

**Comment by qortex** [comment]
Sorry for the delayed reply.
Will look into it to make this import optional.

**Comment by bmtheo** [comment]
@dsebastien it now possible to not import HttpClientModule :)
You need version 5.0.2
