### ISSUE TITLE
Add import HttpClientModule to README Installation

### ISSUE THREAD

**Issue by mikegoodstadt** [dbfannin/ngx-logger#137]
Should the Installation guide in the README include importing HttpClientModule?
An error occurs without this import and importing resolves the issue (see [StackBlitz](https://stackblitz.com/edit/angular-ngx-logger)).
```
import { HttpClientModule } from '@angular/common/http';
...
imports: [ ..., HttpClientModule, ...]
```
(I think this is what is being referenced in #131 and #133.)

**Comment by gloriousjob** [comment]
Agreed. I actually avoided upgrading until I figured this out recently. Not sure if the following note is helpful:

imports: [
BrowserModule,
// import HttpClientModule after BrowserModule.
HttpClientModule,
...
],
