### ISSUE TITLE
Logging delegate

### ISSUE THREAD

**Issue by rcollette** [dbfannin/ngx-logger#139]
I would like to delegate the actual HTTP call that is made to another logging library, in this case js-sumo-logger
https://github.com/SumoLogic/js-sumo-logger

Is there any mechanism for doing this (cancelable events? callback?)

If not, it would be a helpful feature to add.

**Comment by dbfannin** [comment]
You can do this by implementing a NGXLoggerMonitor. See the docs for more details. Thanks!
