### ISSUE TITLE
[Feature Request]: ServerLogging- Enable buffering POST requests 

### ISSUE THREAD

**Issue by arielnahom** [dbfannin/ngx-logger#141]
Hi,
i couldn't find any way to buffer (debounce) the POST requests done to the server, in order to reduce the frequency and amount of requests done to the server.
what i mean is - queuing log events for configured time and writing them in batch'es

it would be great to configure a buffer for remote server debugging.
similar to 
thanks.

**Comment by hypery2k** [comment]
I would love have this feature. But I think to get this working, we should add also a new backend which is accepting an array of log entries and then debounce them. I would stick a configurable timeframe to collect log entries and then send them to the backend

**Comment by dbfannin** [comment]
I would suggest using a custom NGXLoggerMonitor that handles your backend requests. This is outside the scope of NGX Logger. Thanks!
