### ISSUE TITLE
Line# and file name are not from ts file

### ISSUE THREAD

**Issue by SenthilKumar76** [dbfannin/ngx-logger#143]
Hi,
Thanks for the Fantastic library !

I am trying to do a simple test and am logging from Angular component, but the logger is showing the line number from the compiled js file.. instead of the *.ts file.

It'll be great if you can provide an option to display the line# from the ts file, is it much useful for debugging

Thanks a lot
SK

Sample Code:
![2019-09-07 17_11_00-home component ts](https://user-images.githubusercontent.com/16273141/64472565-ff4a4a80-d192-11e9-9a8a-e4cc6252ab04.png)

Console output:
![2019-09-07 17_11_43-Microsoft Edge](https://user-images.githubusercontent.com/16273141/64472564-ff4a4a80-d192-11e9-8e39-b0bcbdfc7244.png)

**Comment by mike-kolback** [comment]
You may need to enable source maps in your app.module
