### ISSUE TITLE
[Feature Request] Adding Client Information

### ISSUE THREAD

**Issue by hypery2k** [dbfannin/ngx-logger#145]
Would be awesome to have a build-in functionality for adding browser and other client info as log information.
For this somekind of log sesssion id needs to created and hold in memory.

If you think that could be interesting I would sent a PR

**Comment by dbfannin** [comment]
@hypery2k, Sorry for the late response. I think this would lie outside of the scope of NGX Logger. I would encourage you to use a custom NGXLoggerMonitor to do this.
