### ISSUE TITLE
Injection of logger instance into http interceptor not working

### ISSUE THREAD

**Issue by brgrz** [dbfannin/ngx-logger#146]
For some reason, the logger instance in below code is always undefined although the logger works elsewhere within the app. The logger is configured in main app module but I also tried configuring it in the Shared module where the ErrorInterceptorService is. Did not work either (undefined in constructor). Is there something special about interceptors why this wouldn't work?

```
import { NGXLogger } from 'ngx-logger';

@Injectable({
	providedIn: 'root'
})
export class ErrorsInterceptorService implements HttpInterceptor {

	constructor(private logger: NGXLogger) { }

handleError(error: HttpErrorResponse) {

// this.logger undefined here
	this.logger.error(error.message);
	return throwError(error);
}

```

**Comment by dbfannin** [comment]
this issue is unrelated to NGX Logger, but instead is the nature of HTTP Interceptors. This looks like it's the same issue you're having https://stackoverflow.com/questions/52165619/angular-6-service-is-undefined-after-injecting-in-interceptor
