### ISSUE TITLE
[Feature Request] console.table() support

### ISSUE THREAD

**Issue by jbh** [dbfannin/ngx-logger#147]
I skimmed through the issues and didn't see this mentioned anywhere. Is it possible to support `console.table()`?

**Comment by jbh** [comment]
I'm happy to look into committing the support myself, but I wanted to ask before writing something that broke some standard here.

**Comment by dbfannin** [comment]
@jbh, sorry for the late response. I'm not sure console.table() would add a lot of value. The most common use of logs is to "spit out the data" not necessarily format that data in a specific way. I'm afraid adding support for console.table() would add an unnecessary layer of complexity. 

Would be more than happy to receive any other support/ideas you might have for NGX Logger. Thanks!

**Comment by jbh** [comment]
Maybe I'm misunderstanding. This is the introduction to NGX Logger:

NGX Logger is a simple logging module for angular (currently supports angular 6+). It allows "pretty print" to the console, as well as allowing log messages to be POSTed to a URL for server-side logging.

I interpret that to mean that I can conveniently use NGX Logger to simultaneously output logs to the console while in development, and then send those logs silently to a server when in production. I had a nicely formatted logging system that printed easy to read tables to the console, and I started to convert that to NGX Logger, however, there's the issue that NGX Logger is not compatible with console tables.

Do you have any suggestions for this use case? I want a cohesive environment that all use and go through the logger service. It'd break that design if I had to make exceptions just for console table...
