### ISSUE TITLE
Issue with certain log maps

### ISSUE THREAD

**Issue by joeypedicini92** [dbfannin/ngx-logger#148]
I'm trying to use the enableSourceMap config and it's working for some cases. But sometimes when I log I get a bunch of 404s for `GET http://localhost:4200/.map 404 (Not Found)`

and when that log gets spit out it looks something like `2019-10-03T01:20:53.871Z DEBUG [    at http:NaN] parseHash callback`

It seems to mainly happen if I log in a callback of a vendor function. Though I'm not 100% sure on this.

Running in development mode with source maps enabled. Tried debugging through the mapper service but I'm not totally sure why this is happening.  Let me know what debug information would help

**Comment by cm253** [comment]
We are facing the same problem and the pull request works as expected. Hopefully it will be merged soon.

**Comment by dbfannin** [comment]
PR changes published in ngx-loger@4.0.6. Thanks @martin-reiterer!
