### ISSUE TITLE
timestamp in logObject is always in new Date().toISOString() in logger.service.ts

### ISSUE THREAD

**Issue by ahm-minxianli** [dbfannin/ngx-logger#149]
In line 174 `(const timestamp = new Date().toISOString();`) within logger.service.ts, timestamp is always converting to toISOString(), it will be great that timestamp is in local timezone. Is there a plan to fix it or any workaround to fix this issue?

**Comment by dbfannin** [comment]
@ahm-minxianli, This has been requested before. #159 is in progress. If it does not go through, I will make the changes. Keep an eye out!

**Comment by MicMicMon** [comment]
Now #160 in progress :)

**Comment by ahm-minxianli** [comment]
@dbfannin @MicMicMon  Thanks for the update. I will check once the PR is merged.

**Comment by dbfannin** [comment]
thanks to @MicMicMon for the PR. custom timestamps now supported using the date pipe ngx-logger@4.1.0
