### ISSUE TITLE
Concurrent requests for the same source-maps file

### ISSUE THREAD

**Issue by martin-reiterer** [dbfannin/ngx-logger#151]
With activated SourceMaps, it can happen that the same SourceMap file has to be loaded several times from the server. This occurs, for example, if several log outputs in the same file are executed in quick succession. The reason is that the loading process of the SourceMap file is pending but the same SourceMap file is needed for the next log output. In these cases it is queried again from the backend.

As a result, this can lead to a chronologically incorrect order of the log outputs within the same file. This occurs, for example, if a request to a SourceMap file executed later receives a result from the server before a request executed earlier.

<img width="837" alt="Bildschirmfoto 2019-10-20 um 11 15 55" src="https://user-images.githubusercontent.com/11654016/67157408-c07be880-f32b-11e9-8fbc-3961022351f3.png">

**Comment by dbfannin** [comment]
@martin-reiterer, your PR changes were published in ngx-logger@4.0.6. Thanks again!
