### ISSUE TITLE
Server-Side Logging / Log Level as String

### ISSUE THREAD

**Issue by lunanigra** [dbfannin/ngx-logger#165]
Hello, just evaluating NGX Logger server-side logging against ELK stack. Basically it works out-of-the-box.

The log level is sent as number (e.g. debug = 1). Is this really common? Isn't it more user fiendly and safer sending the log level as string? Means in my case directly sending 'DEBUG' to Logstash.

Thanks, JC

**Comment by dbfannin** [comment]
@lunanigra, correct, it's using the enum value when passing the web request. If you wish to manipulate the payload before it gets sent, take a look at Custom Log Monitoring. Cheers!

**Comment by 121arunkumar** [comment]
@lunanigra  did u get the result whatever u wanted? if yes can u help.

Thanks

**Comment by lunanigra** [comment]
@121arunkumar you can use this custom log monitor.

```
import {NGXLoggerMonitor, NGXLogInterface, NgxLoggerLevel } from 'ngx-logger';

export class MyLoggerMonitor implements NGXLoggerMonitor {
  onLog(log: NGXLogInterface) {
    (log as {})['level'] = NgxLoggerLevel[log.level];
  }
}
```

Then register the monitor at a central place (e.g. within AppComponent).

```
export class AppComponent {
  constructor(private oauthService: OAuthService, logger: NGXLogger) {
    logger.registerMonitor(new MyLoggerMonitor())
  }
}
```
@dbfannin however I'm not sure if this solution is really cool. You have to cast the log object as NGXLogInterface requires an Enum. I don't see the benefit of sending severity level as number (0, 1, 2, ...). A string is much more user friendly or easier to filter, e.g. when analysing server logs via Kibana.

**Comment by dougse** [comment]
@lunanigra - Wondering, I'm trying to log to docker elk sebp/elk on port 9200  i keep getting CORs errors, I'm unable to configure ELK to offer CORs - do you have any ELK config tips? (Thanks)

**Comment by deefdragon** [comment]
@dougse I kept running into the same thing. 

the following in the input worked for me to "disable" cors
```
        http {
                port => 5000
                        response_headers => {
                        "Access-Control-Allow-Origin" => "*"
                        "Content-Type" => "text/plain"
                        "Access-Control-Allow-Headers" => "Origin, X-Requested-With, Content-Type, Accept"
                }
        }
```
