### ISSUE TITLE
issues in file name and line number 

### ISSUE THREAD

**Issue by ArpithaGMGowda** [dbfannin/ngx-logger#167]
![image](https://user-images.githubusercontent.com/40782788/73421975-8324ef00-434d-11ea-8ba2-13a1a82a017a.png)

![image](https://user-images.githubusercontent.com/40782788/73422088-d303b600-434d-11ea-9b86-7676d9ed8ba3.png)

i am saving logs into JSON file as well , but the issue is file name and line number is same. its not changing and for all bugs i am getting same file name.

Kindly help on this, Thank you in advance :)

**Comment by dlmoffett** [comment]
I am experiencing the same issue:
![image](https://user-images.githubusercontent.com/39200073/73969372-87ff1b00-48d8-11ea-81a2-71a7752bafb0.png)

I attempted the fix suggested in this thread, near the bottom: https://github.com/dbfannin/ngx-logger/issues/69 (specifically the issue related to `vendor` source maps: https://stackoverflow.com/questions/55690465/vendorsourcemap-deprecated-in-angular-cli-7-2/56669585#56669585).

Unfortunately the problem persists: all `fileName:lineNumbers` reported by `ngx-logger` are identical.
The reported `fileName:lineNumber` in my case is the *first* place I invoke `logger.trace|debug|log|etc...` in my app. Specifically, from my screenshot the line that reads `11:55:20 AM INFO [./src/app/app.component.ts:68] ##### Burrowing Owl Started #####` is giving the *correct* `fileName:lineNumber`, but then all others are given at that same `fileName:lineNumber` independent of the actual location in source where the log statement is invoked.

Here's some more configuration details (which may or may not be related/useful) in my case:

**package.json**
```
  "dependencies": {
    "ngx-logger": "^4.1.1",
    ...
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular/cli": "~8.3.23",
    ...
   }
```

**angular.json**
```
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "burrowing-owl-client:build",
            "sourceMap": {
              "scripts": true,
              "styles": true,
              "vendor": true
            }
          },
```

**LoggerModule setup**
```
    LoggerModule.forRoot({
      level: environment.defaultLogLevel,
      serverLogLevel: NgxLoggerLevel.OFF,
      enableSourceMaps: environment.enableLoggingSourceMap,
      timestampFormat: 'mediumTime'
    }),
```
**Note:** from my screenshot we can see that `environment.defaultLogLevel = 0` & `environment.enableLoggingSourceMap = true` at run time.

**Comment by ArpithaGMGowda** [comment]
Thank you :)  for your help 


Don't configure or don't import  **NGXLogger** into the app.component.ts, it will print only filename  as app.component.ts ,  if your using multiple component configure into every component, example: test component configure into test.component.ts , if u go to particular page it will show correct file name, I think it will work 

![image](https://user-images.githubusercontent.com/40782788/74003054-471a0b80-4997-11ea-8578-e217c66face5.png)



and I have a another **Doubt** i want to store the logs into the flat file , do you know how is it ? and also i want to change the format of the logs too 
if know this please help on this

**Comment by mcpierce** [comment]
> Thank you :) for your help
> 
> Don't configure or don't import **NGXLogger** into the app.component.ts, it will print only filename as app.component.ts , if your using multiple component configure into every component, example: test component configure into test.component.ts , if u go to particular page it will show correct file name, I think it will work

I don't believe this to be true. We're not importing NGXLogger into our AppComponent, only in other components. But this bug pathology still exists in our app.

**Comment by mcpierce** [comment]
> Thank you :) for your help
> 
> Don't configure or don't import **NGXLogger** into the app.component.ts, it will print only filename as app.component.ts , if your using multiple component configure into every component, example: test component configure into test.component.ts , if u go to particular page it will show correct file name, I think it will work

If you configure it in each module, then the first lazy module loaded is the one that shows this pathology; i.e., I load it in my "service-network" module, and now ALL logs show as coming from the first component in that module that was loaded.

**Comment by dlmoffett** [comment]
Interesting.

I have created a separate `logging` *module*. In the `logging.module` is where I initialize `NGXLogger`. 
This module...
- ...*provides* a separate `LoggerConfigurationService` used for dynamically changing the `NGXLogger` configuration
- ...*exports* the NGX `LoggerModule`

My `logging.module` then gets imported throughout my app into other modules. Throughout the components/services in these modules I rely on Angular's dependency injection to get a reference to the `NGXLogger` in the standard way.

**App structure**
```
- /app
	- /modules
		- /logging
			- logging.module.ts
		- /other-module
			- other-module <-- Imports logging.module
		- /some-other-module
			- some-other-module <-- Imports logging.module
	app.module.ts <-- Imports logging.module
```

**logging.module.ts**
```
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    HttpClientModule,
    LoggerModule.forRoot({
      level: environment.defaultLogLevel,
      serverLogLevel: NgxLoggerLevel.OFF,
      enableSourceMaps: environment.enableLoggingSourceMap,
      timestampFormat: 'mediumTime'
    }),
    StoreModule.forFeature(loggingFeatureKey, loggingReducer),
    EffectsModule.forFeature([LoggingEffects])
  ],
  providers: [LoggerConfigurationService],
  exports: [
    LoggerModule
  ]
})
export class LoggingModule { }
```

**app.module.ts**
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
  	...etc,
    LoggingModule,
  ],
  providers: [reducerProvider],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**other.module.ts**
```
@NgModule({
  declarations: [...etc],
  imports: [
    ...etc,
    LoggingModule,
  ]
})
export class OtherModule { }
```

**Example usage in a service in the `other` module**
```
@Injectable({
  providedIn: 'root'
})
export class OtherModuleService {

  constructor(private logger: NGXLogger)
  }

  doSomethingThatLogs() {
    ...
    this.logger.debug(`Some stuff`)
  }
}
```

**Comment by yzhan407** [comment]
Hi, I don't have this problem, the path seems to be correct. But the line number seems to be wrong.
I followed the usage steps on <a href="https://github.com/dbfannin/ngx-logger">This page</a>, and I also created standalone logger with its own config every time when I use it.
Here is the response that I got on the test server that I set on my local machine.


{'message': 'close modal test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:16:37 PM', 'fileName': './src/app/shared/modal/modal.component.ts', 'lineNumber': '27'}  \
127.0.0.1 - - [28/Feb/2020 16:16:37] "POST /echo HTTP/1.1" 200 -   \
127.0.0.1 - - [28/Feb/2020 16:16:42] "OPTIONS /echo HTTP/1.1" 200 - \
{'message': 'here is the test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:16:42 PM', 'fileName': './src/app/post/post.component.ts', 'lineNumber': '45'}\
127.0.0.1 - - [28/Feb/2020 16:16:42] "POST /echo HTTP/1.1" 200 -  \
{'message': 'close modal test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:16:43 PM', 'fileName': './src/app/shared/modal/modal.component.ts', 'lineNumber': '27'}\
127.0.0.1 - - [28/Feb/2020 16:16:43] "POST /echo HTTP/1.1" 200 -\
127.0.0.1 - - [28/Feb/2020 16:17:07] "OPTIONS /echo HTTP/1.1" 200 -\
{'message': 'here is the test error', 'additional': [], 'level': 5, 'timestamp': 'Feb 28, 2020, 4:17:07 PM', 'fileName': './src/app/post/post.component.ts', 'lineNumber': '45'}\
127.0.0.1 - - [28/Feb/2020 16:17:07] "POST /echo HTTP/1.1" 200 - \
{'message': 'here is the test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:17:10 PM', 'fileName': './src/app/post/post.component.ts', 'lineNumber': '45'}\
127.0.0.1 - - [28/Feb/2020 16:17:10] "POST /echo HTTP/1.1" 200 -   

in this case test error and test warning all happens on the same file in ./src/app/post/post.component.ts, but that should not be the case, test error is on line 45 which happens first, test error happens on line 51 which happens secondly. But on the log, it shows the same line. Could you please help to look into this?

**Comment by yzhan407** [comment]
> Hi, I don't have this problem, the path seems to be correct. But the line number seems to be wrong.
> I followed the usage steps on [This page](https://github.com/dbfannin/ngx-logger), and I also created standalone logger with its own config every time when I use it.
> Here is the response that I got on the test server that I set on my local machine.
> 
> {'message': 'close modal test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:16:37 PM', 'fileName': './src/app/shared/modal/modal.component.ts', 'lineNumber': '27'}
> 127.0.0.1 - - [28/Feb/2020 16:16:37] "POST /echo HTTP/1.1" 200 -
> 127.0.0.1 - - [28/Feb/2020 16:16:42] "OPTIONS /echo HTTP/1.1" 200 -
> {'message': 'here is the test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:16:42 PM', 'fileName': './src/app/post/post.component.ts', 'lineNumber': '45'}
> 127.0.0.1 - - [28/Feb/2020 16:16:42] "POST /echo HTTP/1.1" 200 -
> {'message': 'close modal test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:16:43 PM', 'fileName': './src/app/shared/modal/modal.component.ts', 'lineNumber': '27'}
> 127.0.0.1 - - [28/Feb/2020 16:16:43] "POST /echo HTTP/1.1" 200 -
> 127.0.0.1 - - [28/Feb/2020 16:17:07] "OPTIONS /echo HTTP/1.1" 200 -
> {'message': 'here is the test error', 'additional': [], 'level': 5, 'timestamp': 'Feb 28, 2020, 4:17:07 PM', 'fileName': './src/app/post/post.component.ts', 'lineNumber': '45'}
> 127.0.0.1 - - [28/Feb/2020 16:17:07] "POST /echo HTTP/1.1" 200 -
> {'message': 'here is the test warning', 'additional': [], 'level': 4, 'timestamp': 'Feb 28, 2020, 4:17:10 PM', 'fileName': './src/app/post/post.component.ts', 'lineNumber': '45'}
> 127.0.0.1 - - [28/Feb/2020 16:17:10] "POST /echo HTTP/1.1" 200 -
> 
> in this case test error and test warning all happens on the same file in ./src/app/post/post.component.ts, but that should not be the case, test error is on line 45 which happens first, test error happens on line 51 which happens secondly. But on the log, it shows the same line. Could you please help to look into this?

I solved my problem using @vinimaz suggestion on issue #166 
I have posted my solution there following his advice there. I am not sure if that is the right ay ot if that solves that issue. but just for reference here in case anyone needed

**Comment by qortex** [comment]
Close here and follow-up in #187
