### ISSUE TITLE
save  the logs in flat file 

### ISSUE THREAD

**Issue by 121arunkumar** [dbfannin/ngx-logger#170]
i am able to store all the logs on the server but it is showing in json format.and also want to change the field of logs.
i m referring this (https://github.com/mwellner/angular-logging) to store the logs on server, 

Thanks in advance

**Comment by dbfannin** [comment]
see the examples of Custom Log Monitoring in the readme. Use a log monitor, you get access to all logs, and you can then do with it, whatever you like. store it in your preferred format, as well as change the structure of the payload. I hope this helps!

**Comment by 121arunkumar** [comment]
Thanks @dbfannin. I have used your  custom log monitor but it is not reflecting any changes  in that component. and do i  need to change anything in the custom log monitor which u provided?  and it will be very helpful if you can provide that custom log monitor which can print the logs in flat file and we can change the fields also. i m new in angular so i m confused.

Thanks in advance

**Comment by dbfannin** [comment]
@121arunkumar the idea is that you register your own log monitor with the ngx logger. (see the docs) this log monitor onLog() gets called with every time the logger methods are called. In this class you can then manipulate the json payload or do whatever you want with it.

So there are a few steps in getting started

1.  create a log monitor class that implements NGXLoggerMonitor
  ```
import {NGXLoggerMonitor, NGXLogInterface} from 'ngx-logger';
 
  export class MyLoggerMonitor implements NGXLoggerMonitor {
    onLog(log: NGXLogInterface) {
      // this is where you manipulate the log into whatever format you wish and transport it wherever you want it to go.
      console.log('myCustomLoggerMonitor', log);
    }
  }
```
2. register the log monitor with your logger (this can be done in a component or a service)
```
  import {NGXLogger} from 'ngx-logger';
  import {MyLoggerMonitor} from './my-logger-monitor';
 
  export class MyService {
    constructor(private logger: NGXLogger) {
      this.logger.registerMonitor(new MyLoggerMonitor())
 
      this.logger.error('BLAHBLAHBLAH');
    }
  }
```
3. ensure that your logger config is set correctly. It will both call your log monitor and the http service if you have your config set up that way. you will most likely want to set serverLogLevel to off.

that should be all you need to do. Good luck!

**Comment by 121arunkumar** [comment]
Thanks @dbfannin .it really helped.

**Comment by 121arunkumar** [comment]
@dbfannin,  I have tried that but in the console it is showing as i want but on the server side and in the file it is showing like below.

 {
      "message": "error",
      "level": 5,
      "timestamp": "2020-02-14T07:15:19.812Z",
      "fileName": "./src/app/app.component.ts",
      "lineNumber": "20",
      "id": 274
    },
    {
      "message": "error",
      "level": 5,
      "timestamp": "2020-02-14T09:27:22.200Z",
      "fileName": "./src/app/app.component.ts",
      "lineNumber": "20",
      "id": 275
    }
  ].
can i get this data in the below format.
error |  ERROR | 2020-02-14T07:15:19.812Z | ./src/app/app.component.ts| 20

**Comment by dbfannin** [comment]
post your code and I'll help you work through it. It looks like you're still relying on ngx-logger to make the http requests, but your custom log monitor should handle making the request. you should disable the http request in ngx-logger

**Comment by 121arunkumar** [comment]
Thanks a lot @dbfannin.
I m sharing  all the files in which i have changed.In the mylogmonitor.ts i have used console.log so it is printing on the console in which format i want. same thing i want in flat file.(like below)

**error message | ERROR | 2020-02-14T07:15:19.812Z | ./src/app/app.component.ts| 20**
**debug message | DEBUG| 2020-02-14T07:15:19.812Z | ./src/app/app.component.ts| 134**


**http.service.ts** :

 import { Injectable } from '@angular/core';
import {HttpBackend, HttpRequest, HttpResponse} from '@angular/common/http';
import { Observable } from 'rxjs';
import {filter, map} from 'rxjs/operators';
import { NGXLogInterface } from './types/ngx-log.interface';

@Injectable()
export class NGXLoggerHttpService {
  constructor(private readonly httpBackend: HttpBackend) { }

  logOnServer(url: string, log: any, options: object): Observable<any> {
    // HttpBackend skips all HttpInterceptors
    // They may log errors using this service causing circular calls
    const req = new HttpRequest<any>('POST', url, log, options || {});
    return this.httpBackend.handle(req).pipe(
      filter(e => e instanceof HttpResponse),
      map<HttpResponse<any>, any>((httpResponse: HttpResponse<any>) => httpResponse.body)
    );
  }

}

**mylogmonitor.ts:**

 import {NGXLoggerMonitor, NGXLogInterface} from 'ngx-logger';
import { HttpBackend } from '@angular/common/http';

export class MyLoggerMonitor implements NGXLoggerMonitor {
  onLog(log: NGXLogInterface) {
      
    console.log(log.message + log.timestamp);
  }
}

**app.component.ts:**
import { Component, OnInit } from '@angular/core';
import { NGXLogger } from "./logger.service";
import { MyLoggerMonitor } from './mylogmonitor';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  title = 'log';

  constructor(private logger: NGXLogger) {
    // this.logger.debug("Debug message");
    // this.logger.info("Info message");
    // this.logger.log("Default log message");a
    // this.logger.warn("Warning message");
    // this.logger.error("Error message");
    this.logger.registerMonitor(new MyLoggerMonitor());
    this.logger.error('error');
    this.logger.debug('debug');
  }

  ngOnInit() {
  //  this.logger.debug( "error message");
}
}

**logger.service.ts:** 
  import { Inject, Injectable, PLATFORM_ID } from '@angular/core';
import { HttpErrorResponse, HttpHeaders, HttpParams } from '@angular/common/http';
import { isPlatformBrowser } from '@angular/common';

import { NGXLoggerHttpService } from './http.service';
import {LogPosition} from './types/log-position';
import { NgxLoggerLevel } from './types/logger-level.enum';
import { LoggerConfig } from './logger.config';
import { NGXLoggerConfigEngine } from './config.engine';
import { NGXLoggerUtils } from './utils/logger.utils';
import { NGXLoggerMonitor } from './logger-monitor';
import { NGXLogInterface } from './types/ngx-log.interface';
import { NGXMapperService } from './mapper.service';

export const Levels = [
  'TRACE',
  'DEBUG',
  'INFO',
  'LOG',
  'WARN',
  'ERROR',
  'FATAL',
  'OFF'
];


@Injectable()
export class NGXLogger {
  private readonly _isIE: boolean;
  private readonly _logFunc: Function;
  private config: NGXLoggerConfigEngine;
  private _customHttpHeaders: HttpHeaders;
  private _customParams: HttpParams;
  private _withCredentials: boolean = false;

  private _loggerMonitor: NGXLoggerMonitor;
  sss: any;

  constructor(private readonly mapperService: NGXMapperService, private readonly httpService: NGXLoggerHttpService,
              loggerConfig: LoggerConfig, @Inject(PLATFORM_ID) private platformId) {
    this._isIE = isPlatformBrowser(platformId) && navigator && navigator.userAgent &&
      !!(navigator.userAgent.indexOf('MSIE') !== -1 || navigator.userAgent.match(/Trident\//) || navigator.userAgent.match(/Edge\//));

    // each instance of the logger should have their own config engine
    this.config = new NGXLoggerConfigEngine(loggerConfig);

    this._logFunc = this._isIE ? this._logIE.bind(this) : this._logModern.bind(this);

  }

  public trace(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.TRACE, message, additional);
  }

  public debug(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.DEBUG, message, additional);
  }

  public info(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.INFO, message, additional);
  }

  public log(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.LOG, message, additional);
  }

  public warn(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.WARN, message, additional);
  }

  public error(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.ERROR, message, additional);
  }

  public fatal(message, ...additional: any[]): void {
    this._log(NgxLoggerLevel.FATAL, message, additional);
  }

  public setCustomHttpHeaders(headers: HttpHeaders) {
    this._customHttpHeaders = headers;
  }

  public setCustomParams(params: HttpParams) {
    this._customParams = params;
  }

  public setWithCredentialsOptionValue(withCredentials: boolean) {
    this._withCredentials = withCredentials;
  }

  public registerMonitor(monitor: NGXLoggerMonitor) {
    this._loggerMonitor = monitor;
  }

  public updateConfig(config: LoggerConfig) {
    this.config.updateConfig(config);
  }

  public getConfigSnapshot(): LoggerConfig {
    return this.config.getConfig();
  }

  private _logIE(level: NgxLoggerLevel, metaString: string, message: string, additional: any[]): void {

    // Coloring doesn't work in IE
    // make sure additional isn't null or undefined so that ...additional doesn't error
    additional = additional || [];

    switch (level) {
      case NgxLoggerLevel.WARN:
        console.warn(`${metaString} `, message, ...additional);
        break;
      case NgxLoggerLevel.ERROR:
      case NgxLoggerLevel.FATAL:
        console.error(`${metaString} `, message, ...additional);
        break;
      case NgxLoggerLevel.INFO:
        console.info(`${metaString} `, message, ...additional);
        break;
      default:
        console.log(`${metaString} `, message, ...additional);
    }
  }

  
  

  private _log(level: NgxLoggerLevel, message, additional: any[] = [], logOnServer: boolean = true): void {
    const config = this.config.getConfig();
    const isLog2Server = logOnServer && config.serverLoggingUrl && level >= config.serverLogLevel;
    const isLogLevelEnabled = level >= config.level;

    if (!(message && (isLog2Server || isLogLevelEnabled))) {
      return;
    }

    const logLevelString = Levels[level];

    message = typeof message === 'function' ? message() : message;
    message = NGXLoggerUtils.prepareMessage(message);

    // only use validated parameters for HTTP requests
   // const validatedAdditionalParameters = NGXLoggerUtils.prepareAdditionalParameters(additional);

    const timestamp = new Date().toISOString();

    // const callerDetails = NGXLoggerUtils.getCallerDetails();
    this.mapperService.getCallerDetails(config.enableSourceMaps).subscribe((callerDetails: LogPosition) => {
      const logObject: NGXLogInterface = {
        message: message,
      //  additional: validatedAdditionalParameters,
        level: level,
        timestamp: timestamp,
        fileName: callerDetails.fileName,
        lineNumber: callerDetails.lineNumber.toString()
      };

      

      if (this._loggerMonitor && isLogLevelEnabled) {
        this._loggerMonitor.onLog(logObject);
      }

      if (isLog2Server) {
        // make sure the stack gets sent to the server
        message = message instanceof Error ? message.stack : message;
        logObject.message = message;

        const headers = this._customHttpHeaders || new HttpHeaders();
        headers.set('Content-Type', 'application/json');

        const options = {
          headers: headers,
          params: this._customParams || new HttpParams(),
          responseType: config.httpResponseType || 'json',
          withCredentials: this._withCredentials
        };



        // Allow logging on server even if client log level is off
        this.httpService.logOnServer(config.serverLoggingUrl, logObject, options).subscribe((res: any) => {
            // I don't think we should do anything on success
          },
          (error: HttpErrorResponse) => {
            this._log(NgxLoggerLevel.ERROR, `FAILED TO LOG ON SERVER: ${message}`, [error], false);
          }
        );
      }


      // if no message or the log level is less than the environ
      if (isLogLevelEnabled && !config.disableConsoleLogging) {
        const metaString = NGXLoggerUtils.prepareMetaString(timestamp, logLevelString,
          callerDetails.fileName, callerDetails.lineNumber.toString());

        return this._logFunc(level, metaString, message, additional);
      }
    });
  }
}

**app.module.ts:** 
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HttpClientModule } from "@angular/common/http";
import{NGXLogger} from './logger.service'
import { NgxLoggerLevel} from "ngx-logger";
import { CustomNGXLoggerService } from './custom-logger.service';
import { NGXLoggerHttpService } from './http.service';
import { LoggerModule } from './logger.module';
import {NGXMapperService} from './mapper.service';
//import { environment } from 'src/environments/environment';
//import { ModuleWithProviders } from '@angular/core';





@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    LoggerModule,
    LoggerModule.forRoot({
      serverLoggingUrl: "http://localhost:3000/logs", // needs json-server running
      level: NgxLoggerLevel.DEBUG,
     serverLogLevel: NgxLoggerLevel.INFO,
    // level:environment.logLevel,
      //serverLogLevel: environment.serverLogLevel,
      enableSourceMaps:true,
      disableConsoleLogging: true,
   //   timestampFormat:'shortDate'
    }),
  
  ],
  providers: [CustomNGXLoggerService, NGXLoggerHttpService,NGXLogger,  NGXMapperService],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(private logger: NGXLogger){}

 }

**Comment by ArpithaGMGowda** [comment]
> @121arunkumar the idea is that you register your own log monitor with the ngx logger. (see the docs) this log monitor onLog() gets called with every time the logger methods are called. In this class you can then manipulate the json payload or do whatever you want with it.
> 
> So there are a few steps in getting started
> 
> 1. create a log monitor class that implements NGXLoggerMonitor
> 
> ```
> import {NGXLoggerMonitor, NGXLogInterface} from 'ngx-logger';
> 
> export class MyLoggerMonitor implements NGXLoggerMonitor {
>   onLog(log: NGXLogInterface) {
>     // this is where you manipulate the log into whatever format you wish and transport it wherever you want it to go.
>     console.log('myCustomLoggerMonitor', log);
>   }
> }
> ```
> 
> 1. register the log monitor with your logger (this can be done in your app.component.ts or a service, but you should only do it in things that will be instantiated once or you will end up registering the monitor multiple times)
> 
> ```
>   import {NGXLogger} from 'ngx-logger';
>   import {MyLoggerMonitor} from './my-logger-monitor';
>  
>   export class MyService {
>     constructor(private logger: NGXLogger) {
>       this.logger.registerMonitor(new MyLoggerMonitor())
>  
>       this.logger.error('BLAHBLAHBLAH');
>     }
>   }
> ```
> 
> 1. ensure that your logger config is set correctly. It will both call your log monitor and the http service if you have your config set up that way. you will most likely want to set serverLogLevel to off.
> 
> that should be all you need to do. Good luck!


what to mention in onlog  function ??

In Winston package we will use like this ... but in NGX-Logger ??
i am confused to what to add in NGX-logger 

export const logger = createLogger({
  transports: [
     new transports.File({
      filename: "error1.log",
      level: "debug",
      format: format.combine(format.timestamp({
      format: 'YYYY-MM-DD HH:mm:ss'
    }),format.simple())
    }),
    new transports.File({
      filename: "info1.log",
      level: "info",
      format: format.combine(format.timestamp(), format.json())
    }),
  ]
});

**Comment by dbfannin** [comment]
@121arunkumar you sent quite a lot of code. I didn't read through all of it. If you've made changes in any NGX-Logger code, you need to revert that. You should not be making any changes to the library itself

This first thing is you need to change how you're importing the module. Notice we've removed the serverLoggingUrl and turned serverLogLevel to OFF. this is because you will be handling this functionality in your custom log monitory

**app.module.ts:**
```
LoggerModule.forRoot({
    level: NgxLoggerLevel.DEBUG,
    serverLogLevel: NgxLoggerLevel.OFF,
    enableSourceMaps:true,
    disableConsoleLogging: true,
}),
```

The second thing you need to do is properly implement the NGX Log Monitor. In the code you sent, the only thing you're doing is logging the message and timestamp. You must format it, and make your HTTP reqest in the log monitor

**mylogmonitor.ts:**

```
import {NGXLoggerMonitor, NGXLogInterface} from 'ngx-logger';
import { HttpClient } from '@angular/common/http';

export class MyLoggerMonitor implements NGXLoggerMonitor {
    private readonly _url = '/logs';
    constructor(private http: HttpService) {

    }
    onLog(log: NGXLogInterface) {
        //TODO:
        // 1. format the log however you wish it to be formatted
        const formattedLog: string = log.message + log.timestamp;

        // 2. Make the HTTP Request
        this.http.post(this._url, formattedLog).subscribe();
    }
}
```


I'm not sure how you're wanting to format or what the type of format your HTTP Endpoint accepts, so you will have to figure the rest out on your own. Good luck!

**Comment by dbfannin** [comment]
@ArpithaGMGowda, If you are wanting to use with Winston, follow the example above except in your custom log monitor, instead of HTTP post, log with your Winston logger

**Comment by 121arunkumar** [comment]
Thanks a lot @dbfannin.

**Comment by Sandeep4141** [comment]
> @121arunkumar you sent quite a lot of code. I didn't read through all of it. If you've made changes in any NGX-Logger code, you need to revert that. You should not be making any changes to the library itself
> 
> This first thing is you need to change how you're importing the module. Notice we've removed the serverLoggingUrl and turned serverLogLevel to OFF. this is because you will be handling this functionality in your custom log monitory
> 
> **app.module.ts:**
> 
> ```
> LoggerModule.forRoot({
>     level: NgxLoggerLevel.DEBUG,
>     serverLogLevel: NgxLoggerLevel.OFF,
>     enableSourceMaps:true,
>     disableConsoleLogging: true,
> }),
> ```
> 
> The second thing you need to do is properly implement the NGX Log Monitor. In the code you sent, the only thing you're doing is logging the message and timestamp. You must format it, and make your HTTP reqest in the log monitor
> 
> **mylogmonitor.ts:**
> 
> ```
> import {NGXLoggerMonitor, NGXLogInterface} from 'ngx-logger';
> import { HttpClient } from '@angular/common/http';
> 
> export class MyLoggerMonitor implements NGXLoggerMonitor {
>     private readonly _url = '/logs';
>     constructor(private http: HttpService) {
> 
>     }
>     onLog(log: NGXLogInterface) {
>         //TODO:
>         // 1. format the log however you wish it to be formatted
>         const formattedLog: string = log.message + log.timestamp;
> 
>         // 2. Make the HTTP Request
>         this.http.post(this._url, formattedLog).subscribe();
>     }
> }
> ```
> 
> I'm not sure how you're wanting to format or what the type of format your HTTP Endpoint accepts, so you will have to figure the rest out on your own. Good luck!






Hi @dbfannin :) 
i am getting error after following above code in **app.component.ts**
```
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { NGXLogger } from './logger.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private logger:NGXLogger) {
   this.logger.registerMonitor(new MyLoggerMonitor());
    this.logger.error('BLAHBLAHBLAH');
  }
}
```
**myloggermonitor.ts**

```
import {NGXLoggerMonitor, NGXLogInterface} from 'ngx-logger';
import { HttpClient } from '@angular/common/http';
export class MyLoggerMonitor implements NGXLoggerMonitor {
 // private http: HttpClient;
  private _url = /log1';
  //public http: Http;
  constructor(private httpClient: HttpClient) {
  }
 onLog(log: NGXLogInterface,) {
const formattedLog: string = log.message + log.timestamp;
this.httpClient.post(this._url, formattedLog).subscribe((data:any)=>{
  console.log('myCustomLoggerMonitor', data);
});
 }
}
```



**Error is** 

```
ERROR in src/app/app.component.ts:18:31 - error TS2554: Expected 1 arguments, but got 0.    
      this.logger.registerMonitor(new MyLoggerMonitor());               
          src/app/my-logger-monitor.ts:10:15
        constructor(private httpClient: HttpClient) {
              An argument for 'httpClient' was not provided.
```

In Console :
```
ERROR TypeError: Cannot read property 'post' of undefined
    at MyLoggerMonitor.onLog (my-logger-monitor.ts:19)
    at SafeSubscriber._next (logger.service.ts:191)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at SwitchMapSubscriber.notifyNext (switchMap.js:70)
    at InnerSubscriber._next (InnerSubscriber.js:11)
    at InnerSubscriber.next (Subscriber.js:49)
    at ReplaySubject.next (Subject.js:39)
```
