### ISSUE TITLE
Logging with substitution strings does not work

### ISSUE THREAD

**Issue by xinthose** [dbfannin/ngx-logger#171]
`this.logger.info("hello %s", "world");` yields this in the log: `hello %s` instead of `hello world`.  In my case, I use subsitiution strings for objects to look pretty in the console, but then they do not show in my log:

**This code**
```
let test = {
    "data1": 123,
    "data2": "sdfsedf",
    "data3": 12.45,
}
this.logger.info("test 0 data = " + JSON.stringify(test));
this.logger.info("test 1 data = %s", JSON.stringify(test));
this.logger.info("test 2 data = %o", test);
this.logger.info("test 3 data = %O", test);
```
**yields this log**
```
[2020-02-19 15:22:34.223710] [INFO] test 0 data = {"data1":123,"data2":"sdfsedf","data3":12.45}
[2020-02-19 15:22:34.228140] [INFO] test 1 data = %s
[2020-02-19 15:22:34.247732] [INFO] test 2 data = %o
[2020-02-19 15:22:34.248285] [INFO] test 3 data = %O
```

**Comment by dbfannin** [comment]
@xinthose, we do not support substitutions in NGX Logger. Instead, we expect you to format the string before you pass it into the logger. To "pretty print" JSON.stringify() all you have to do is pass in a couple extra params.

`this.logger.info("test 0 data = " + JSON.stringify(test, null, 2));`

the 3rd param in JSON.stringify is the number of spaces you want to add before each line. I hope this helps.

**Comment by xinthose** [comment]
@dbfannin OK.  Thank you sir.
