### ISSUE TITLE
Feature request: Customize more / or disable file & line number

### ISSUE THREAD

**Issue by qortex** [dbfannin/ngx-logger#174]
There are open issues on file & line numbers not working properly. It seems to be a complicated problem to solve, and I'm bitten by the same bug as #166  :
![image](https://user-images.githubusercontent.com/37897072/75755499-09f33000-5d2f-11ea-8b47-9b284e50a1c4.png)

I have an additional issue: I wrapped the logger calls in my own service, and as you can see it is thus always the same spot that is being reported (actually, the first spot called, as explained in #166).

So:

1. It would be nice to have a config option to set the level of depth to look for the actual call. Here, I need to go back 1 step further in the callstack to show the proper place.
2. It would be nice to be able to disable the line display altogether, it might not be useful at all. Just disabling the `sourceMaps` option just shows the un-sourcemapped file, but still displays something.

Is it something that could be easily achieved? If positive, I could take a stab at a PR.

Note: what's weird is that it actually worked that way a few weeks ago - but then disappeared. Don't remember what set of updates had that effect because I changed lots of stuff in my project moving to Angular 9.

**Comment by tjandro93** [comment]
Just wanted to drop in and say this would be a really useful feature

**Comment by amilor** [comment]
#192 this one is for your first feature request, but simplified to only allow offset of +1, that is when `NGXLogger` is used in a custom `LoggerService`. I don't think that customizable caller offset is required, you either call the logger itself or put it inside a wrapper service.

**Comment by Raphy** [comment]
I've made a PR to allow to disable the file details : #214

**Comment by bmtheo** [comment]
PR #214 of @Raphy was approved and merged into master, now waiting for @qortex to validate #192 and then this feature request will be completed

**Comment by bmtheo** [comment]
ok #192 is merged now so I close this issue
