### ISSUE TITLE
Catch Error in Errorhandler and log exact place of where error occurs

### ISSUE THREAD

**Issue by yzhan407** [dbfannin/ngx-logger#175]
Hi,
  I would like to catch errors globally using by implements ErrorHandler provided by Angular. And I want to use ngx-logger inside this ErrorHandler. My use case right now is something like this:
![image](https://user-images.githubusercontent.com/23008677/76109456-77f75b80-5faa-11ea-9f76-99e0937681be.png)
In this case, the message part of the error logs are all the information including 

" Error: custom error here
    at PostComponent.clearPostsData (http://localhost:4200/post-post-module.js:92:15)" 
etc...

and the line number is where this logger is called, in my case, it is always line 11. This is reasonable because I called the logger here. (So this is NOT the case as recent issue 166 and 167)
So I am wondering if we can pass the error object into the logger directly, so that every time the Errorhandler is called and an error is passed into the logger, we can still get the correct line number and filename where originally where the error occurs in logger output.

I did not see an issue according to ErrorHandler from what I know, so I opened a new one. If there is another issue about this or this is already a solution, I will close this issue.
Thanks

**Comment by qortex** [comment]
I guess this would mean going further up in the callstack in that specific case.
Not sure what would be the logic to decide when to do that or not.

Let's integrate this feature request in the thinking about file names & numbers issues, a common solution might be possible.

**Comment by valdeua** [comment]
Do you have a plan to improve it?

**Comment by qortex** [comment]
Yes, I'll include that in a not so distant todo :)

**Comment by bmtheo** [comment]
The PR #192 would fix this issue because you would be able to use proxiedSteps to go further up the callstack and ignore your handleError

**Comment by bmtheo** [comment]
#192 just got merged so I close this issue
