### ISSUE TITLE
already using a another server in project 

### ISSUE THREAD

**Issue by ArpithaGMGowda** [dbfannin/ngx-logger#179]
Hi 
In our project we are already using one server, i don't want to use another server
any solution ??

Thank you in advance :)

**Comment by qortex** [comment]
Can you clarify with a more concrete example? I don't quite understand the issue.
Thanks!

**Comment by qortex** [comment]
I'll close this issue and will be happy to reopen it in case you are able to clarify the use case here.
Best,
