### ISSUE TITLE
"logglytrackingsession" is not a secure cookie

### ISSUE THREAD

**Issue by sadiqrajani** [dbfannin/ngx-logger#180]
A cookie associated with a resource at http://example.com was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

**Comment by qortex** [comment]
Can you give more details on the use case, and why you think it's related to `ngx-logger`?

**Comment by maroy1986** [comment]
This has nothing to do with ngx-logger... I was evaluating that library for inclusion in our project and I looked at the code. There's no place where cookies are read/created...

@sadiqrajani  If I were you, I would definitely check with the [Loggly](https://www.loggly.com/) support team. That's an issue on their end, not this library here.

**Comment by qortex** [comment]
I will close this issue since the issue seems not related to `ngx-logger`. Feel free to reopen it with additional information.
