### ISSUE TITLE
Is this package has been deprecated ?????

### ISSUE THREAD

**Issue by ArpithaGMGowda** [dbfannin/ngx-logger#183]
![image](https://user-images.githubusercontent.com/40782788/77424927-e97f3880-6df7-11ea-8203-393c63ccc680.png)

What is this ?? if i open https://www.npmjs.com/package/ngx-logger this its show like **Package has Been Deprecate**d

**Comment by alvaromartmart** [comment]
Unfortunately, it seems so. Maybe the author @dbfannin could share his reasons to deprecate the project?

- If it's a matter of compatibility with the latest release of Angular, I already [submitted a PR that should solve the errors](https://github.com/dbfannin/ngx-logger/pull/173), but I don't think it has been reviewed.
- If the author does not have time to mantain the package ATM, maybe he could ask the community if anyone would be up to collaborate reviewing PRs, issues etc?

I personally think it would be a shame that this package is deprecated, given its popularity. It's a great way to enhance logging on Angular projects...

**Comment by ArpithaGMGowda** [comment]
People are used this package in there real time project ,  just imagine there Plight :( 
lot of people used this package and spend time on this :(


is there any other Package related to Logging for Angular ???

**Comment by dbfannin** [comment]
Hey guys. Glad to hear that the package is useful and people are still very interested in keeping it around. I no longer have the time to support the project and give it the level of attention it needs. I did try to reach out and ask for more help from the community, and a few people have responded. That support is greatly appreciated, with the responding to issues and submitting PRs.

I would love to see the project continue. If someone is passionate about continuing this project, please reach out to me and I will transfer the package over to you. I just don't have the time to maintain it well right now.

Thanks!

**Comment by ArpithaGMGowda** [comment]
ya please wait , someone will come to continue this project  :)

**Comment by MicMicMon** [comment]
> I would love to see the project continue. If someone is passionate about continuing this project, please reach out to me and I will transfer the package over to you. I just don't have the time to maintain it well right now.

Interested! Never maintained an Angular package before, but interested to learn & help improve `ngx-logger` over time.
How should I reach out?

**Comment by maxisam** [comment]
@dbfannin I would love to maintain this project if you want. I have used it for a while. 
Thank you for this wonderful package.

**Comment by alvaromartmart** [comment]
I'd like to help too.

**Comment by dbfannin** [comment]
@MicMicMon, @maxisam, @alvaromartmart, Thank you guys so much for reaching out to help maintain the project! I've added you all as collaborators to the project on github, I've also created a Discord server for us to use to collaborate. Join it, and I can get your npm info from there and add you to the project on NPM. We can also use this discord server to post release notes, etc. Click the link below to join the server!

https://discord.gg/QYwfun

**Comment by dbfannin** [comment]
Anyone is welcome to join the discord server, even if you don't want to be a maintainer of the project

**Comment by dbfannin** [comment]
This packages is no longer deprecated. closing this issue

**Comment by ArpithaGMGowda** [comment]
Thank you so much :)
