### ISSUE TITLE
Set server log level after the initial startup

### ISSUE THREAD

**Issue by marcopierobon** [dbfannin/ngx-logger#184]
Hey,

I'm trying to change the server log level after the startup in my SPA.

Namely, what I expect to happen is:
- App loads
- Logger sets to defaults
- Logger config loaded from the backend
- Bearer token fetched
- Logger config updated with desired server logging level
- Bearer token added to the logger

The reason why I need to do it, is that the bearer token ought to be obtained during the user session.

The code I wrote does not seem to update the ngxlogger instance, so the server logging stays disabled.

Based on the recommendations I found on another issues here, here's the code I wrote:

(app,module.ts)

	import { LoggerModule } from 'ngx-logger';

	@NgModule({
		imports: [
			...
			LoggerModule.forRoot(null)
		],

		declarations: [
			AppComponent
		],
		providers : [
			...
		],
		bootstrap: [AppComponent]
	})

(app.component.ts)

	import { initLogger } from './shared/logging/tsLogger';

	@Component({
		...
	})

	export class AppComponent implements OnInit, OnDestroy {
		
		constructor(private authService: AuthService,
			logger: NGXLogger) {
			initLogger(logger);
		}

	}
		

(tsLogger.ts)

    import {NGXLogger} from 'ngx-logger';

    export let singletonLogger: NGXLogger;

    export const initLogger = (newLogger: NGXLogger) => singletonLogger = newLogger;

(config.service.ts)

    	import { NgxLoggerLevel, NGXLogger } from 'ngx-logger';
	import { singletonLogger, initLogger } from '../../shared/logging/tsLogger';

	@Injectable()
	export class ConfigService {
		public config: Config = {} as Config;
		public ngxLoggerLevel: NgxLoggerLevel;

		constructor(
			private http: HttpClient,
			private logger: NGXLogger) {
			
		}

		loadConfigSettings(): Promise<void> {
			return this.http
				.get<Config>('/appsettings.json')
				.toPromise()
				.then(data => {
					this.config = data;
					this.configureLogging();
				});
		}

		configureLogging() {
			var logLevelFromNetApp = this.config.Logging.LogLevel.Default;
			var loggingUrl = (this.config.LogginUrl).replace(/([^:]\/)\/+/g, "$1");;

			var ngxLoggingLevel = NgxLoggerLevel.ERROR;
			if (logLevelFromNetApp == "Trace") {
				ngxLoggingLevel = NgxLoggerLevel.TRACE;
			}
			else if (logLevelFromNetApp == "Debug") {
				ngxLoggingLevel = NgxLoggerLevel.DEBUG;
			}
			else if (logLevelFromNetApp == "Information") {
				ngxLoggingLevel = NgxLoggerLevel.INFO;
			}
			else if (logLevelFromNetApp == "Warning") {
				ngxLoggingLevel = NgxLoggerLevel.WARN;
			}
			else if (logLevelFromNetApp == "Error") {
				ngxLoggingLevel = NgxLoggerLevel.ERROR;
			}
			else if (logLevelFromNetApp == "Critical") {
				ngxLoggingLevel = NgxLoggerLevel.FATAL;
			}
			else if (logLevelFromNetApp == "None") {
				ngxLoggingLevel = NgxLoggerLevel.OFF;
			}
			if (singletonLogger == null) {
				initLogger(this.logger);
			}

			singletonLogger.updateConfig({
				level: ngxLoggingLevel,
				serverLoggingUrl: loggingUrl,
				serverLogLevel: NgxLoggerLevel.OFF,
				disableConsoleLogging: !this.config.Logging.IsConsoleLoggingOn,
				enableSourceMaps: this.config.Logging.EnableSourceMaps,
				timestampFormat: "full"
			});

			this.ngxLoggerLevel = ngxLoggingLevel;
		}

		public setLoggingBearerTokenForServerRequests(bearerToken: string) {
			if (singletonLogger != null && bearerToken != null) {
				singletonLogger.updateConfig({ level: this.ngxLoggerLevel, serverLogLevel: this.ngxLoggerLevel });
				singletonLogger.setCustomHttpHeaders(new HttpHeaders({ 'Authorization': 'Bearer ' + bearerToken }));
			}
		}

	}

As soon as I get the bearer token, I call the configService.setLoggingBearerTokenForServerRequests setting the token and updating the logging level, but it keeps staying OFF.

I assume it has to do with DI, but I would assume there is only one instance of the logger. What am I doing wrong?

**Comment by mario45211** [comment]
`updateConfig()`  is an atomic operation - it will overwrite previous configuration - it was described in another issue as I remember.

You can copy previous configuration using `getConfigSnaphot()` method in second `updateConfig()` call.

**Comment by qortex** [comment]
Thanks for opening this issue!
Adding additional context from a similar issue. Will take a precise look at that.

Additional context: https://github.com/dbfannin/ngx-logger/issues/109

**Comment by amilor** [comment]
`NGXLogger#updateConfig()` is not merging the configuration you pass in with the current logger config, it completely overwrites it with the one you provided.

```ts
// this overwrites your configuration, so it will only contain level and serverLogLevel properties, 
// the serverLoggingUrl property is not present in the configuration anymore so server logging is disabled
singletonLogger.updateConfig({ level: this.ngxLoggerLevel, serverLogLevel: this.ngxLoggerLevel });
```

The method works as expected and updates the configuration of given logger instance with the one you provided, if you want to merge the config you must obtain the current config and first merge the new config into it and pass that merge object into the `updateConfig()` method.

Also there is no need for the `singletonLogger`, if you provide the the `NGXLogger` in the app root then the instance will be a singleton by default.

**Comment by bmtheo** [comment]
@marcopierobon you just need to call updateConfig and it will work
As others explained you need to getConfig first because updateConfig overwrites it completely

Here is an example from the demo app on the repo
```
  handleLogLevelChange(newLevel: NgxLoggerLevel) {
    const updatedConfig = this.logger.getConfigSnapshot();
    updatedConfig.level = newLevel;
    updatedConfig.serverLogLevel = newLevel;
    this.logger.updateConfig(updatedConfig);
  }
```

I am closing this issue
