### ISSUE TITLE
[Enhancement] Manipulate message field in monitor

### ISSUE THREAD

**Issue by mario45211** [dbfannin/ngx-logger#185]
Consider below NGXLoggerMonitor:
```
export class LogMapper implements NGXLoggerMonitor {

  onLog(log: NGXLogInterface): void {
    log.additional = log.additional.map(it => JSON.stringify(it));
    let msg = log.message;
    for (const obj in log.additional) {
      msg = msg.replace('{}', obj);
    }
    log.message = msg;
  }
}
```
where I want to replace all '{}' placeholders with passed additional objects (SLF4J-like). Unfortunately, in class `NGXLogger` there is below logic:
```
 const logObject: NGXLogInterface = {
        message: message, //<---- first message copy
        additional: validatedAdditionalParameters,
        level: level,
        timestamp: timestamp,
        fileName: callerDetails.fileName,
        lineNumber: callerDetails.lineNumber.toString()
      };

      if (this._loggerMonitor && isLogLevelEnabled) {
        this._loggerMonitor.onLog(logObject); // monitor's execution
      }

      if (isLog2Server) {
        // make sure the stack gets sent to the server
        message = message instanceof Error ? message.stack : message;
        logObject.message = message; //<----- second message copy, overwriting (ignoring) changes in monitor
//....
```
which ignore `message` changes in my custom monitor.

Is that behaviour is expected or it can be changed to include `message` changes in log's monitor ?

**Comment by HackPoint** [comment]
@mario45211 How you actually monitor this in production? How do you protect yourself from ppl to get to your logs?

**Comment by bmtheo** [comment]
@mario45211 the monitor is not supposed to edit the log behavior, it's just here so we can add behaviors

There is a way to do what you want, by disabling logs and logging it yourself in the monitor, ask me if you want an example (this is not perfect but this is the only way for now)

**Comment by mario45211** [comment]
@HackPoint sorry for the very late answer, I must miss some notification ;( 
Could you clarify what you mean by "ppl to get to your logs" ?

@bmtheo "the monitor is not supposed to edit the log behavior" - that's understandable. 
This issue is just an ask for a "nice-to-have" feature, which I'm familiar from Java's SLF4J lib (not sure it's should be labelled as ~bug). Logging object's details is sometimes tricky if I forget  wrapping it with `JSON.stringify()` :)

**Comment by bmtheo** [comment]
Hi @mario45211 
The feature is now "properly" available
To do such thing you need to customise log behavior (doc is here : https://github.com/dbfannin/ngx-logger/blob/master/docs/customising.md)

In your case you would need to extends NGXLoggerMetadataService and tweak the message in there

Starting example:
```
export class myCustomMetadataService extends NGXLoggerMetadataService{
  public getMetadata(
    level: NgxLoggerLevel,
    config: INGXLoggerConfig,
    message?: any | (() => any),
    additional?: any[],
  ): INGXLoggerMetadata {
    const metadata = super.getMetadata(level, config, message, additional);
    // tweak behavior, ex : metadata.message = metadata.message + 'added message';
    return metadata;
}
```
