### ISSUE TITLE
Issues with filenames & line numbers

### ISSUE THREAD

**Issue by qortex** [dbfannin/ngx-logger#187]
Several issues refer to unexpected output in filenames & line numbers. This issue merges those reports and will be used to track progress on this matter.

Issues (they will be closed and tracked here):
#129 
#166 
#167

**Comment by rattkin** [comment]
#192

**Comment by Epsiom** [comment]
Is there any progress on the issue regarding Firefox logs?

**Comment by bmtheo** [comment]
@Epsiom #228 that just got merged fixes some issues with firefox logs, it might be enough for what you needed

**Comment by qortex** [comment]
Closing this since v4.2.0 & upcoming v4.2.1 should fix this. Fixed by #230 & #231 .
Please open a new issue if it's not the case.
