### ISSUE TITLE
Log timestramp/level color is unreadable on dark theme console

### ISSUE THREAD

**Issue by maroy1986** [dbfannin/ngx-logger#188]
Hey there!

I was trying your library and I noticed that the `Trace` color on Google Chrome dark theme is unreadable. See for yourself :
![image](https://user-images.githubusercontent.com/2490360/79155257-dcbe8680-7d9e-11ea-918d-c0011e8000f2.png)

I'll make a PR for changing this pretty soon.

**Comment by qortex** [comment]
Fixed in 4.1.7 by #189 , thanks for the PR!
