### ISSUE TITLE
Configuring NGXLogger for library components

### ISSUE THREAD

**Issue by miohtama** [dbfannin/ngx-logger#195]
I have an Angular library that internally uses `NGXLogger`.

When I include the library in an Angular `app.module.ts` I do it like this:

```ts
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    MyLibraryModule,
    LoggerModule.forRoot({
      level: NgxLoggerLevel.DEBUG,
    }),
  ],
```

The logging works if I log from the application components. However if I log from a library component, I get:

```
core.js:6185 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[Web3Service -> NGXLogger -> LoggerConfig -> LoggerConfig -> LoggerConfig]: 
  NullInjectorError: No provider for LoggerConfig!
NullInjectorError: R3InjectorError(AppModule)[Web3Service -> NGXLogger -> LoggerConfig -> LoggerConfig -> LoggerConfig]: 
  NullInjectorError: No provider for LoggerConfig!
    at NullInjector.get (core.js:1076)
    at R3Injector.get (core.js:16629)
    at R3Injector.get (core.js:16629)
    at R3Injector.get (core.js:16629)
    at injectInjectorOnly (core.js:931)
    at Module.ɵɵinject (core.js:941)
    at Object.NGXLogger_Factory [as factory] (ngx-logger.js:812)
    at R3Injector.hydrate (core.js:16865)
    at R3Injector.get (core.js:16617)
    at injectInjectorOnly (core.js:931)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41264)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
```

The workaround for this is to specify a library specific LoggerConfig. In my library module I can do

```

@NgModule({
  declarations: [...],
  imports: [
    CommonModule,
    ClarityModule,
    HttpClientModule,
    LoggerModule
  ],
  exports: [
   ....
  ],
  providers: [
    { provide: LoggerConfig,  useValue: { level: NgxLoggerLevel.DEBUG} },
  ]
})
export class Web3Module { }
```

However if I do this, then the library logging configure is separate from the application logging configuration. 

This is Angular 9. Am I misunderstanding something in Angular dependency injection or why do not library components get their `LoggingConfig` when I initialize ngx-logger in the `app.module.ts`? Do I need to somehow specifically tell imported modules to use the same logging config as the app does?

**Comment by dbfannin** [comment]
@miohtama, for your library, you should be using `LoggerModule.forChild()` and `LoggerModule.ForRoot()` in your app module.

**Comment by miohtama** [comment]
@dbfannin Understood! Will try this out today.

**Comment by fabioformosa** [comment]
@miohtama have you solved? I get the same error, but I have also a feature module in my app.
I've opened an other issue #197

**Comment by miohtama** [comment]
@fabioformosa No, even if I have a similar configuration and structure as in #197 I am still getting hit by this error. Trying to figure out if there is something I have missed, or there is some cache that needs to be emptied.

**Comment by fabioformosa** [comment]
Have you rebuilt library? Is your library within the project structure or outside in a seperate repo?

**Comment by miohtama** [comment]
@fabioformosa I am using project structure from Angular generator, everything is in `/projects`. Both app and library are built in the same `tsconfig.json`.

**Comment by fabioformosa** [comment]
@miohtama It's right: `LoggerModule.forChild()` in `mylib`, `LoggerModule.forRoot({some logging config})` in `demoapp`.
You should build `mylib` with `ng build mylib` after each change, and in `demoapp` all imports must be like `import something from 'mylib'` and not with relative path `import something from '..\..\mylib\src'`.
So, I solved.

**Comment by miohtama** [comment]
Ok. I ended up solving this, but solving it little differently.

My module provides its own `forRoot` which takes the logger config as an argument from the ap:

```ts
/**
 * Web3module importer.
 *
 *
 */
@NgModule({
  declarations: [...t],
  imports: [
    CommonModule,
    ...
    LoggerModule.forChild(),
  ],
  exports: [
...
  ],
})
export class Web3Module {

  /**
   * Oriignally forRoot() was added due to issues with server-side rendering.
   *
   * See also https://github.com/dbfannin/ngx-logger/issues/195
   *
   * @param web3Config Configuration for Web3 service
   * @param loggerConfig  Configuration how we use ngx-logger
   */
  static forRoot(web3Config: Web3Config, loggerConfig: LoggerConfig): ModuleWithProviders<Web3Module> {
    return {
      ngModule: Web3Module,
      providers: [
        { provide: LoggerConfig,  useValue: loggerConfig },
        { provide: Web3Config,  useValue: web3Config },
      ]
    };
  }
}
```

Then you import the library module like:

```ts
// Demo app has always full logging
const loggerConfig: LoggerConfig = {
  level: NgxLoggerLevel.DEBUG,
};

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    LoggerModule.forRoot(loggerConfig),
    Web3Module.forRoot(
      web3config,
      loggerConfig,
    ),
    UiModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

````
