### ISSUE TITLE
Source mapping result inaccurate with build optimization turned on

### ISSUE THREAD

**Issue by amilor** [dbfannin/ngx-logger#196]
When building (or serving) a project with build optimization set to true, the source mapping shows incorrect information.

`angular.json`:
![image](https://user-images.githubusercontent.com/7261682/80676401-f2c68980-8ab6-11ea-9c42-ac88ac35c173.png)

With `ng serve`:
Line information is: `[(webpack)-dev-server/client/clients/BaseClient.js:13]`
![image](https://user-images.githubusercontent.com/7261682/80676472-1f7aa100-8ab7-11ea-9ea4-c3f621b80ee2.png)

With `ng build`:
Line informatin is: `[node_modules/rxjs/_esm2015/internal/observable/empty.js:3]`
![image](https://user-images.githubusercontent.com/7261682/80676579-5d77c500-8ab7-11ea-9f66-58bf49a78ea3.png)

**Expected result:**
Line information: `[./src/app/core/services/environment.service.ts:50]`
![image](https://user-images.githubusercontent.com/7261682/80676750-be070200-8ab7-11ea-8fee-b1bb557912a1.png)

**Comment by qortex** [comment]
Does the just released `proxiedSteps` feature solve your issue by allowing to see the right caller?

As for the `ng build` part, unfortunately the file information might be lost along the way when code optimization kicks in, it would need some investigation depending on your first results I guess.

**Comment by bmtheo** [comment]
Hi @amilor 
Any chance you try again to see if the issue still stands ?
The v5 was just published and it changes a good portion of the code
