### ISSUE TITLE
Not working in aot mode

### ISSUE THREAD

**Issue by thegitty** [dbfannin/ngx-logger#2]
It seems that the logger is working in jit, but not aot mode.

Working: ng serve
Not working: ng serve --aot

Having the module imported in app.module.ts
`
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    LoggerModule.forRoot(loggerConfig)
  ],`

Error message:
`
ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve 'ngx-logger/ngx-logger' in '/Users/......./src/$$_gendir/app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 26:0-50
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts`

**Comment by dbfannin** [comment]
Can you share some code that shows how you're importing the logger? It appears to be compiling successfully for me using using AOT. See below:

```
$ ng serve -aot
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 075ea2cf000160626c37                                                               
Time: 43610ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 304 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 748 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 226 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 21.5 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.66 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
```

**Comment by thegitty** [comment]
Thanks for the quick reply. 

After migrating from Angular 2.x to Angular 4.x it seems not be be an issue anymore.

If you can confirm that behavior, the README.md could be fixed:

> NGX Logger is a simple logging module for angular 2

**Comment by dbfannin** [comment]
Yes that is correct. This was an update of ng2.logger to work with angular 4. I will make sure the README gets updated. Sorry for the confusion.
