### ISSUE TITLE
Support Angular 9

### ISSUE THREAD

**Issue by timKraeuter** [dbfannin/ngx-logger#200]
I have updated my project to Angular 9. Everything still seems to work, but when doing "npm install" I get the following warning:

```

npm WARN ngx-logger@4.0.3 requires a peer of @angular/common@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-logger@4.0.3 requires a peer of @angular/core@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
```

It would be cool if the framework could officially support Angular 9.

Thanks in advance!

**Comment by qortex** [comment]
The package already supports Angular 9, you just need to update to latest version 4.1.5 (it was updated a few versions ago).

So make sure your `package.json` allows this version and update.
