### ISSUE TITLE
Angular 7 can not see any error in log

### ISSUE THREAD

**Issue by protradeshare-admin** [dbfannin/ngx-logger#201]
Example:
https://stackblitz.com/edit/angular-ngx-logger-example?file=app%2Fapp.component.ts

What I am doing wrong?

**Comment by simonmatt** [comment]
I opened your angular stackblitz on my browser, the `ngx-logger` messages can be printed on my side, please see below:
```
2020-05-28T13:17:29.379Z [DEBUG] Your log message goes here
2020-05-28T13:17:29.383Z [DEBUG] Multiple Argument support
2020-05-28T13:17:29.389Z [ERROR] Error message
```

**Comment by qortex** [comment]
Same here, the logging works ok on the posted Stackblitz.
I'll close this issue for now, please add more context & a reproducible scenario and we'll take a look at it.
