### ISSUE TITLE
ngx-logger does not log automatically for unhandled error

### ISSUE THREAD

**Issue by vinodkpasi** [dbfannin/ngx-logger#205]
Does ngx-logger support for automatic error logging for unhandled error or do we need to catch unhandled error at application level and log the error manually?
I have used other logger like log4net, winston they support this kind of feature.

**Comment by Pommes9485** [comment]
It does not support it ootb as far as I can tell. But you can implement it very easy:
Add an errorhandler:
`import { ErrorHandler, Injectable } from '@angular/core';
import { NGXLogger } from 'ngx-logger';

@Injectable({
    providedIn: "root"
  })
export default class MyErrorHandler extends ErrorHandler {

    constructor(private logger: NGXLogger) {
        // The true paramter tells Angular to rethrow exceptions, so operations like 'bootstrap' will result in an error
        // when an error happens. If we do not rethrow, bootstrap will always succeed.
        super();
    }

    handleError(error) {
        // send the error to the server
        this.logger.error(error);
        // delegate to the default handler
        super.handleError(error);
    }
}`
Add the errorhandler to to provide-statement in app.module.ts:
`  providers: [{ provide: ErrorHandler, useClass: MyErrorHandler }],`

This will intercept every error, send it to the backend and log it afterwards.

**Comment by bmtheo** [comment]
Closing this as the question was answered (the answer is no) and a workaround was provided

**Comment by Ximena-con** [comment]
Hi @MarvinBerger ,  I want to implement the auto-handle of  exception, could you give more details? thanks ~
