### ISSUE TITLE
How pass color arguments to logger

### ISSUE THREAD

**Issue by lagoshny** [dbfannin/ngx-logger#206]
Hi,

Is there a possibility pass color arguments to logger?

For example:

With standard `console.log(`%cHello, %cWorld`, 'color: red;', 'color: blue;')`
The first word Hello will be print with red color, the second with blue color.

I try todo this with NGXLogger: `this.logger.info(`%cHello, %cWorld`, 'color: red;', 'color: blue;')` but all message printed with default gray color.

**Comment by bmtheo** [comment]
Yes you can pass it in the config, it has a colorScheme variable so that you can fully customise it
