### ISSUE TITLE
Log level misunderstood by Chrome console

### ISSUE THREAD

**Issue by albancho** [dbfannin/ngx-logger#213]
When logging a debug (using `this.logger.debug(xxx)`), the message has the correct content, with the prefix "hh:mm:ss DEBUG", but when I want to filter those messages in Chrome, DEBUG is handled as an INFO message.

In Chrome, you are able to choose which level to display: Verbose/Info/Warnings/Errors.  
If I disable "Verbose", nothing happens.  
If I disable "Info", DEBUG logs disappears.

If I manually trigger a `console.debug(xxx)`, it hides when I disable "Verbose", and stays displayed if I disable "Info".

This is annoying when you are on your dev machine, and punctually don't want to see debug logs.

**Comment by bmtheo** [comment]
You are right, this is fixed by #224, it is waiting for review and I'll merge it after
