### ISSUE TITLE
Server side logging happens regardless of whether the user has registered a custom monitor

### ISSUE THREAD

**Issue by kazepis** [dbfannin/ngx-logger#215]
I found out the hard way that the server side logging is not related with the custom monitor registrations.
Reading the sourve code I found out that if the user has registered a custom monitor then it is being used when logging:
```typescript
...
if (this._loggerMonitor && isLogLevelEnabled) {
    this._loggerMonitor.onLog(logObject);
}
...
```
However if you pass a serverUrl the server side logging happens regardless of the custom monitor registration:
```typescript
...
const isLog2Server = logOnServer && config.serverLoggingUrl && level >= config.serverLogLevel;
...
if (isLog2Server) {
        // make sure the stack gets sent to the server
        message = message instanceof Error ? message.stack : message;
        logObject.message = message;

        const headers = this._customHttpHeaders || new HttpHeaders();
        headers.set('Content-Type', 'application/json');

        const options = {
          headers: headers,
          params: this._customParams || new HttpParams(),
          responseType: config.httpResponseType || 'json',
          withCredentials: this._withCredentials
        };
        // Allow logging on server even if client log level is off
        this.httpService.logOnServer(config.serverLoggingUrl, logObject, options).subscribe((res: any) => {
          // I don't think we should do anything on success
        },
          (error: HttpErrorResponse) => {
            this._log(NgxLoggerLevel.ERROR, `FAILED TO LOG ON SERVER: ${message}`, [error], false);
          }
        );
      }
```

When registerign a new custom monitor I would expect to either NOT log on the server OR provide a second method i.e. `onServerSideLogging()` that is being called when the user has passed a server URL.

Eitherway I believe that at least it is worth mentioning in the docs.
Thank you in advance for your time.

**Comment by bmtheo** [comment]
The logMonitor is a "monitor" meaning it does not replace the logger to do its job

But I agree with you this is not as clear as I think it should be and it could be better

Anyway for your problem I have a workaround for you, you can :

- Use `disableConsoleLogging = true` in the config
- Set `serverLogLevel = NgxLoggerLevel.Off` in the config

Then your logMonitor will completely replace the current logger

**Comment by bmtheo** [comment]
I am closing this issue as the use case has a workaround and the monitor should not shadow the server log
I'll have a look if I can improve the doc and the way of overriding the logger behavior
