### ISSUE TITLE
Build error with ngx-logger for Angular 11 project

### ISSUE THREAD

**Issue by nimishdesai1989** [dbfannin/ngx-logger#216]
I am getting below error in build as soon as I import the nx-logger

 Error: node_modules/ngx-logger/lib/logger.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (ngx-logger) which declares LoggerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

I added below two lines in my app.module.ts

import { LoggerModule, NgxLoggerLevel } from 'ngx-logger';

imports: [
LoggerModule.forRoot({ serverLoggingUrl: '/api/logs', level: NgxLoggerLevel.DEBUG, serverLogLevel: NgxLoggerLevel.ERROR })
  ],

can you please help to let me know what is going wrong. I am bit new to Angular.

**Comment by bmtheo** [comment]
Any chance you give us a repro ?

I tried on stackblitz and for me it works perfectly fine
https://stackblitz.com/edit/ngx-logger-4-1-with-angular-11?file=src/app/app.component.ts

**Comment by bmtheo** [comment]
Ok I just tried locally (to avoid any stackblitz specific behavior) and it works fine as well
I'm closing this issue

@nimishdesai1989 if you can give us more info (a reproduction would be best) I will reopen this issue
