### ISSUE TITLE
Method for quick test on current logging level

### ISSUE THREAD

**Issue by ArneMancofi** [dbfannin/ngx-logger#217]
For conditional logging of data that require significant computation, it would be handy with a fast method for checking the current log level. Something like `.isEnabled(level: NgxLoggerLevel): boolean` which could be used like this:
```typescript
if (logger.isEnabled(NgxLoggerLevel.DEBUG)) {
  const details = this.ComputeManyDetails(...);
  logger.debug("Reached this program point", details);
}
```
Currently, one can perform a similar test using
```typescript
if (this.logger.getConfigSnapshot().level <= NgxLoggerLevel.DEBUG <= NgxLoggerLevel.DEBUG) {
  ...
}
```
but the call to `getConfigSnapshot()` performs a clone operation, which defeats the purpose of doing a quick level check.

**Comment by bmtheo** [comment]
this will be fixed by #225 (it also includes the same for serverLogLevel)
