### ISSUE TITLE
Feature Request: Add callback for additional log sinks

### ISSUE THREAD

**Issue by iva2k** [dbfannin/ngx-logger#220]
Feature Request: Add callback for additional log sinks, e.g. to be able to display messages in a Toast.

**Comment by bmtheo** [comment]
I'm not sure why a callback would be of any use here and why don't you display the message in a toast right after your logger call ?

Alternatively, there is the NGXLoggerMonitor that lets you do something for every log call, would that help you ?

**Comment by iva2k** [comment]
The point of a toast would be to insert debugging on e.g. a mobile device, where console is not easily accessible.

Inserting lines after logger and then removing is not ideal. Inserting a single callback is, as all code that is already instrumented with logger code does not have to be touched. Callback is a simple way to extend functionality beyond what is provided.

**Comment by bmtheo** [comment]
Yes I understand, your use case can be done with NGXLoggerMonitor

You can implement the onLog function and this will be called everytime the logger is called

This would look like this :

```typescript
@Injectable()
export class LogForMobileDevices extends NGXLoggerMonitor {
    onLog(logObject: NGXLogInterface): void {
      if (/* Is mobile device check */) {
        /* Display log content in toast */
      }
    }
}
```

Once you have this service ready you need to register it for your logger
```typescript
logger.registerMonitor(myMonitor);
```

Please note that the onLog function will slightly change in v5 but it will still work the same way

**Comment by bmtheo** [comment]
v5 is now out and indeed the onLog function has changed a little
It still allows you to do what you asked for

The function looks like this now:
```
onLog(logObject: INGXLoggerMetadata, config: INGXLoggerConfig): void;
```

Closing the issue
