### ISSUE TITLE
How to add auth token to the custum header ?

### ISSUE THREAD

**Issue by chandrakanth25** [dbfannin/ngx-logger#221]
Could some one please provide an example where to add auth token to the custom header. 
If I pass auth token to the below line of code, its throwing error. please suggest.
this.logger.setCustomHttpHeaders(new HttpHeaders({'X-Custom-Header': '123456'}));

**Comment by bmtheo** [comment]
Please document about your error
What would be good is to have at least :

- Your code setting the header
- The error
- The version you are using

Thanks

**Comment by chandrakanth25** [comment]
Appreciate for your comments.
 The version which I am using is "ngx-logger": "^3.3.6" and Angular 8
 Logging to console is working fine, but when I try to log it to server, it giving unauthorized error, basically all my request should append with headers. this is where I am stuck, how to send headers along with serverLoggingUrl.

Thanks.

**Comment by bmtheo** [comment]
The header works fine, here is a working example with your versions (Angular 8 and ngx-logger 3.3.6)
https://stackblitz.com/edit/angular-8-getting-started-ui7kjx?file=src/app/top-bar/top-bar.component.ts

The unauthorized error is most probably not related to ngx-logger package

To make sure about it, you need to use DevTools of your browser to check for header in the requests

You can ask the community for help if you need (stackoverflow, discord etc...)

**Comment by chandrakanth25** [comment]
Thanks for your quick response, Will go through the link provided, will reach out if I have any questions.

Regards
