### ISSUE TITLE
Bump angular to last version (and other dependencies)

### ISSUE THREAD

**Issue by bmtheo** [dbfannin/ngx-logger#229]
It would be good to bump all the dependencies

We are using Angular 8 when Angular is 11 is available

EDIT : work has started in bump-deb-ang-11 branch

**Comment by qortex** [comment]
You're talking about the demo app right?

**Comment by bmtheo** [comment]
I'm talking about the dependencies in the package.json file

I made a branch to start updating this (see bump-dep-ang-11)

It's not a PR yet because I still have those checks to do : 
- build
- tests
- tsickle is not ready yet for typescript 4, should we wait ?
- demo app
- Angular's NPM packages no longer contain jsdoc comments, which are necessary for use with closure compiler (extremely uncommon). This support was experimental and only worked in some use cases. There will be an alternative recommended path announced shortly.
- If you use TestBed.get, you should instead use TestBed.inject. This new method has the same behavior, but is type safe.

**Comment by xinthose** [comment]
**ng update @angular/core @angular/cli**
```
Package "ngx-logger" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0 || ^7.0.0 || ^8.0.0" (extended), would install "11.2.4").
Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0" (extended), would install "11.2.4").
Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0" (extended), would install "11.2.4").
× Migration failed: Incompatible peer dependencies found.
```

**Comment by bmtheo** [comment]
Yes this issue will fix this error

You can force the update and everything works fine
