### ISSUE TITLE
Fyi: error NG6002

### ISSUE THREAD

**Issue by Tobias243** [dbfannin/ngx-logger#233]
I do not know if this belongs here, so sorry if this is unnecessary but since i saw someone with a similar issue i thought i might post it.

After adding the logger i hat the same Issue as [#Issue-216](https://github.com/dbfannin/ngx-logger/issues/216).

Fix that worked for me: delete the node_modules folder and run a new install.

I am aware, this has nothing to do with your Code (big fan btw) but seems like a general problem with adding modules to Angular 11 ivy.

**Comment by bmtheo** [comment]
Hi, thanks for the information

As mentioned this issue is not directly linked to ngx-logger so I close it, but pretty sure some people stumbled upon this and you helped them :+1: 

PS : Also v5 was just published now so it might fix some issues too
