### ISSUE TITLE
Debug Level Not Printing to Console

### ISSUE THREAD

**Issue by maplion** [dbfannin/ngx-logger#237]
I just began using ngx-logger as it seems to have the features I desire, but for some reason the debug level isn't working at all.  The rest of the levels print fine.  Here is an example of each level printed out with its name

```typescript
        this.logger.trace('TRACE');
        this.logger.debug('DEBUG');
        this.logger.log('LOG');
        this.logger.info('INFO');
        this.logger.warn('WARN');
        this.logger.error('ERROR');
        this.logger.fatal('FATAL');
```

and here are the results -- as you can see, debug didn't even print:

![image](https://user-images.githubusercontent.com/8908849/113489306-b9458d80-9480-11eb-9eb1-4be7a3904933.png)

Angular CLI: 11.2.3
Node: 14.15.5
OS: win32 x64

Angular: 11.2.3
... animations, cdk, cli, common, compiler, core, forms       
... material, material-moment-adapter, platform-browser       
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------     
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/compiler-cli           11.2.4
@angular/flex-layout            11.0.0-beta.33
@angular/language-service       11.2.4
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5

**Comment by bmtheo** [comment]
You need to enable verbose mode in your browser to see the debug level
This is the way browsers handle the debug level

**Comment by maplion** [comment]
@bmtheo Good to know, thanks for the info.
