### ISSUE TITLE
Move away from HttpBackend to HttpClient?

### ISSUE THREAD

**Issue by bjorntj** [dbfannin/ngx-logger#239]
Moving away from HttpBackend would make it possible to use interceptors to add headers for every call, which is needed when using API keys/tokens that is refreshed all the time.

**Comment by bmtheo** [comment]
Hi @bjorntj 

It is now possible to that by customising server.service.ts
The doc on how to customise a behavior is here : https://github.com/dbfannin/ngx-logger/blob/master/docs/customising.md

In your case you need to code your own class
Something like this should work
```
export class myCustomServerService extends NGXLoggerServerService {
  public logOnServer<T>(
    url: string,
    logContent: T,
    options: {
      headers?: HttpHeaders;
      reportProgress?: boolean;
      params?: HttpParams;
      responseType?: 'arraybuffer' | 'blob' | 'json' | 'text';
      withCredentials?: boolean;
    },
  ): Observable<T> {
    // your code that uses HttpClient instead of HttpBackend
}
```
