### ISSUE TITLE
Change LoggerConfig dynamically

### ISSUE THREAD

**Issue by fsteinke** [dbfannin/ngx-logger#24]
It would be very helpful as well if it would be possible to change the LoggerConfig at some point during usage. For example we currently encounter situations where we would like to adjust the level as well as the server url?!

**Comment by dbfannin** [comment]
@fsteinke, I can see how this would be helpful, especially when we implement something for #23. Would you want to take a stab at this? If not, it might take a few days for me to get around to it.

**Comment by jtHunter** [comment]
hi, 

would find this helpful too. e.g. change logLevel based on external config, or even when i want to trace just a dedicated block

**Comment by alfonsoluis** [comment]
I am trying to use **ngxLogger** in a project with different **serverLoggingUrl** configuration for dev and production, is configured in other place so I can't hard code it in my app initialization. I can't access the environment that easily in my **ngModule** app initialization so It would be great if there is a way of setting up this value from a configuration file or an environment key inside for instance, my globalError handler service.  But as it is, ngxLogger.options.serverLoggingUrl is a private option. Any thoughts?

**Comment by dbfannin** [comment]
@jtHunter, @alfonsoluis, @fsteinke, as of 2.1.0, it is now possible to update the config dynamically. See the readme for more details.

Thanks for using NGX Logger!
