### ISSUE TITLE
Angular11 build failed webpack\src\ivy\loader.js

### ISSUE THREAD

**Issue by pcouas** [dbfannin/ngx-logger#241]
Hi

I have just added your last version in an new simple project created with "ng new log3" and complilation failed

Module build failed (from C:/loggers/log3/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: C:\loggers\log3\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at C\loggers\log3\node_modules\@ngtools\webpack\src\ivy\loader.js:42:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[log3.zip](https://github.com/dbfannin/ngx-logger/files/6396672/log3.zip)
I have problem on my computer with many different projects, but i have tested on my wife computer and that's running !!!

Regards

**Comment by bmtheo** [comment]
Hi there
According to the error, it looks like the issue stands in your project and not in ngx-logger, am I wrong ?
```Error: C:\loggers\log3\src\main.ts is missing from the TypeScript compilation```

Anyway I just published v5 so you can try again and see if you still have an issue

**Comment by bmtheo** [comment]
Your issue looks like an internal problem, but anyway I created an issue to merge all Ivy related problems, see #277
