### ISSUE TITLE
debug does not work any more

### ISSUE THREAD

**Issue by ishanuda** [dbfannin/ngx-logger#243]
Hi,
After the update to v4.2.1 with angular 11` logger.debug(''); `not working.
But other methods (log, error, info etc.) works well.

Env details:
"ngx-logger": "^4.2.1",
"@angular/core": "~11.2.12",
"typescript": "^4.0.3",

Thank you

**Comment by bmtheo** [comment]
You need to enable "verbose" mode in your browser

**Comment by ishanuda** [comment]
Hi @bmtheo ,

This was a cool feature added, Is this mentioned in the documentations some where or in the release info.
Because I did not find any info.

Thank you very much

**Comment by bmtheo** [comment]
No it's not mentioned yet but it should !

If you have time feel free to submit a PR

I am closing this issue

**Comment by ishanuda** [comment]
> No it's not mentioned yet but it should !
> 
> If you have time feel free to submit a PR
> 
> I am closing this issue

Updated the change log and created the PR.
Should you require to update the README as well?

**Comment by bmtheo** [comment]
Yes I've done it, thx
Referencing #244
