### ISSUE TITLE
Build for Angular 12 with partial-ivy

### ISSUE THREAD

**Issue by MickL** [dbfannin/ngx-logger#252]
Using ngx-logger in my library I get:

> Error: Failed to compile entry-point ngx-logger (`es2015` as esm2015) due to compilation errors:
> ../../../node_modules/@angular/common/common.d.ts:114:22 - error NG6002: Appears in the NgModule.imports of LoggerModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library (@angular/common) which declares CommonModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Could you make a build with partial-ivy as described here: https://angular.io/guide/creating-libraries ?

**Comment by bmtheo** [comment]
Doing the partial-ivy build would probably remove that error, but you can get around this by removing your node_modules and installing again
It worked for another user, he documented it in #233

**Comment by bmtheo** [comment]
Hi again
I just published v5 of the logger, can you see if you still have the issue ?

**Comment by bmtheo** [comment]
I created an issue to merge all existing issues about Ivy, if you want to see updates please subscribe to #277

Thanks for your feedback
