### ISSUE TITLE
Logging Logger Level by Name instead of Enum

### ISSUE THREAD

**Issue by septst** [dbfannin/ngx-logger#256]
Hello,

First of all, I would like to say that this ngx-logger is brilliant. **What I am about to complain about is probably trivial or more of a personal preference rather than an issue.** I have noticed that the log level is being passed as enum while posting to my api to log/save into mongo db. I think it would be better to log it by log level name for better readability. The below is my table screenshot in which the first entry is a sample entry I have made. I am using the below to log the message body.

```
this.logger.info(
      `The log level is changed from ${NgxLoggerLevel[previousLevel]} to ${NgxLoggerLevel[newLevel]}`);
```

![image](https://user-images.githubusercontent.com/24897814/120036198-62da7280-c01d-11eb-92c5-2c01395e7422.png)

Keep up the good stuff!

Note: I would be happy to contribute.

**Comment by bmtheo** [comment]
Thanks for your message

I'm currently working on v5 where everything will be fully customisable and you will easily be able to add a field or to customise a field sent to the server

Stay tuned :)

**Comment by septst** [comment]
Brilliant! Cheers!

**Comment by bmtheo** [comment]
I'm keeping this issue open and I'll provide the actual answer when the v5 is out so that people finding this issue will have the solution at hand

**Comment by bmtheo** [comment]
For anyone stumbling on the issue, this is now possible
A full example is here "(example) Adds a property to the server log" https://github.com/dbfannin/ngx-logger/blob/master/docs/customising.md
