### ISSUE TITLE
npm conflict zones.js

### ISSUE THREAD

**Issue by jonycoo** [dbfannin/ngx-logger#264]
Hello, 
it does'nt seem to automaticly install version ~0.10.3 of zone.js.
please tell me if its just my local problem.

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Project@0.3
npm ERR! Found: zone.js@0.11.4
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.11.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@10.2.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^10.2.3" from the root project
npm ERR!   peer @angular/core@">6.0.0" from ngx-logger@4.3.3
npm ERR!   node_modules/ngx-logger
npm ERR!     ngx-logger@"4.3.3" from the root project
npm ERR!   1 more (@angular/common)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I have found a (at least tempomary) solution by also putting a dependency to `"zone_old": "npm:zone.js@0.10.3"`

If not do difficult  you could also consider bumping the zone.js version to 0.11.3

**Comment by bmtheo** [comment]
Hi there,
I didn't quite understand your problem, but I just published the v5 so maybe it will fix your issue
