### ISSUE TITLE
 An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by amm95** [dbfannin/ngx-logger#273]
Hi Team,

I'm facing this issue when I try to start my app.

Version used : 4.2.1

ERROR in node_modules/ngx-logger/lib/logger.service.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.
get level(): NgxLoggerLevel;

node_modules/ngx-logger/lib/logger.service.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

 get serverLogLevel(): NgxLoggerLevel;

**Comment by bmtheo** [comment]
Quick look online tells me this is related to package compatibility

Please try to fix your package by making sure typescript/angular/ngxlogger versions are on the same page

If this is still not working, you can reopen and provide a repro so that I can look into it
