### ISSUE TITLE
"Encourage the library authors to publish an Ivy distribution."

### ISSUE THREAD

**Issue by EnricoVogt** [dbfannin/ngx-logger#275]
During the build of a project, angular issues the following message:

`- ngx-logger [es2015/esm2015] (git+https://github.com/dbfannin/ngx-logger.git)
Encourage the library authors to publish an Ivy distribution.`

**Comment by bmtheo** [comment]
Yes I created an issue to merge all existing issues about Ivy, if you want to see updates please subscribe to #277 

Thanks for your feedback
