### ISSUE TITLE
ngx-logger is not compatible with Ivy

### ISSUE THREAD

**Issue by bmtheo** [dbfannin/ngx-logger#277]
We need to make ngx-logger compatible with Ivy

Documentation is here : https://angular.io/guide/creating-libraries#ivy-libraries

Some errors that were sent :
`
ngx-logger [es2015/esm2015] (git+https://github.com/dbfannin/ngx-logger.git) Encourage the library authors to publish an Ivy distribution.
`

and

> Error: Failed to compile entry-point ngx-logger (`es2015` as esm2015) due to compilation errors:
> ../../../node_modules/@angular/common/common.d.ts:114:22 - error NG6002: Appears in the NgModule.imports of LoggerModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library (@angular/common) which declares CommonModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by bmtheo** [comment]
@EnricoVogt @MickL @pcouas just started the branch to fix this issue here https://github.com/dbfannin/ngx-logger/tree/build-partial-ivy

According to angular docs, it should be ready (I just set an option to "partial"), but I don't have much knowledge on how this works
So if any of you can test or provide any relevant infos about this, that would be greatly appreciated

**Comment by MickL** [comment]
I think you should remove enableIvy and then the partial should be all it needs

**Comment by bmtheo** [comment]
Thanks for your feedback

This is what I initially did but I had some build errors

The key thing was to update angular to v13 and then do that

Now it should be all ok, just leaving my PR so I can review it later and then I'll publish the Ivy compatible (see #278)

**Comment by bmtheo** [comment]
Just published 5.0.4 that fixes the issue

**Comment by EnricoVogt** [comment]
Great! Thank you for your work!
