### ISSUE TITLE
V5 Not working with Jest

### ISSUE THREAD

**Issue by KyDenZ** [dbfannin/ngx-logger#281]
I am using ngx-logger in an Angular project and jest for testing. While wanting to go from V4 to V5 of ngx-logger, I have an error message when I run the tests with jest:

```
Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

Details:

    /Users/.../node_modules/ngx-logger/fesm2020/ngx-logger.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as i0 from '@angular/core';
```

I have tried various configuration in jest.config, but cannot find a solution.

**Comment by bmtheo** [comment]
It says
`By default "node_modules is ignored by transformers`
And
`To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config`

So did you try removing `transformIgnoreParterns` from your config ?

**Comment by KyDenZ** [comment]
Yes of course I tried.

I'm trying to make a new angular project to show you the error

**Comment by bmtheo** [comment]
Ok that would be amazing if you have a repro so that I can look into it

**Comment by KyDenZ** [comment]
After hours of research ... It works!

For those who encounter the problem:

Update to the new version just released from `@briebug/jest-schematic` and replace latest from the `@angular-builders/jest` package automatically added with a version greater than or equal to: `13.0.1`

thank you @bmtheo for suggesting solutions!
