### ISSUE TITLE
Setting the log level on an instance not working

### ISSUE THREAD

**Issue by JanPhill** [dbfannin/ngx-logger#282]
Hi,

with v5.0.4 and Angular 13 setting the log level only on an instance does not seem to be working anymore.

I created an example based on the working example from #204 here: https://stackblitz.com/edit/angular-ivy-7rmfqg?file=src/app/app.component.ts

Any help or fix would be greatly appreciated.

Thanks, Jan

**Comment by bmtheo** [comment]
Indeed this does not seem correct

I need to double check Angular DI rules when using providers, the goal of the lib is to match DI behavior so users can do what they want with NGXLogger instances

Note to self : This might be related to how config and configEngine are provided

**Comment by bmtheo** [comment]
As stated in the doc @JanPhill is right, the providers array in component create a new instance of NGXLogger thus it should not share the same config
Source : https://angular.io/guide/providers#injector-hierarchy-and-service-instances
