### ISSUE TITLE
Question: How to use serverLoggingUrl?

### ISSUE THREAD

**Issue by Nirman-Git** [dbfannin/ngx-logger#29]
Apologies for raising such a basic question: 

I have defined serverLoggingUrl as serverLoggingUrl: '/api/logs' whereas there is no routing mentioned for the above URL. 
When I run the Angular 4 application locally, I tried localhost:4200/api/logs to review the logs in the browser and could not get it as there is no routing available.

It would be really helpful if you can elaborately explain the way to use serverLoggingUrl properly?
Is it going to create a /api/logs in the server location?

Thanks in advance for your advice.

**Comment by dsandeepchary** [comment]
Hi, 
The mentioned ` api/logs` is not the routing in your Angular application, it is the endpoint on your server where it can do something with the log sent from the client side.
You have to define the API in your back-end and give it your functionality(what it should do with the log sent from the Angular app).

**Comment by dbfannin** [comment]
Closing this as a non-issue.

**Comment by nitishc83** [comment]
i have same problem ..i can't understand how to post logger

**Comment by dadasokarande** [comment]
I have same problem... I am using ngx-logger with my Angular6-MVC application and I have defined serverLoggingUrl. When i run the application I am able hit the log method from MVC controller. But here I am not aware that how can I get a logged data by logger. What input parameter should i used here to my MVC action method.

**Comment by dadasokarande** [comment]
> I have the same problem... I am using ngx-logger with my Angular 7 - MVC application and I have defined serverLoggingUrl. When i run the application I am able hit the log method from MVC controller which define in serverLoggingUrl.
> 
> But here I am not aware that how can I get a logged data by logger. What input parameter should i used here to my MVC action method to get a data?
> 
> Thanks in advance for your advice.

After trying, I am able to fixed the issue. Below is the server side code:-

                                                                                                                  

        public ActionResult ngxLogger(string message, string level, string timestamp, string fileName)          
        {
               //---- server side log handle method
                return Json("", JsonRequestBehavior.AllowGet);
         }

**Comment by mohit7875** [comment]
@dadasokarande can you please mention serverside file name?and where to add
