### ISSUE TITLE
Suggestion: Allow starting log message on new line

### ISSUE THREAD

**Issue by spyro2000** [dbfannin/ngx-logger#290]
Hi,

It would be much easier to read, if log statements would start after a linebreak after timestamp, file details and line number. This way the actual messages would all be alligned at the same place.

**Currenty:**

```
[Timestamp] [very-long-name-of-some-internal-or-app-component.ts] The actual
custom message
```
**Suggestion (optional):**

```
[Timestamp] [very-long-name-of-some-internal-or-app-component.ts]
The actual custom message
```

Basically, it should be possible to prefix each log message with a '\n'. Maybe there could be an optional config key like 'linebreakBeforeMessage': boolean?

Thank you :)

**Comment by spyro2000** [comment]
Any reaction....? :)

**Comment by bmtheo** [comment]
Yes this is currently possible

You need to overwrite writer.service.ts and then provide it in the module (see more info about this in [customising doc](https://github.com/dbfannin/ngx-logger/blob/master/docs/customising.md))

Code would look like this (untested) :
```
@Injectable()
export class NewLineNGXLoggerWriterService extends NGXLoggerWriterService{

  protected override prepareMetaString(metadata: INGXLoggerMetadata, config: INGXLoggerConfig): string {
    return super.prepareMetaString(metadata, config) + '\n';
  }

}

```

**Comment by spyro2000** [comment]
Many, many thanks. Will try this and report back, if it works. :)

**Comment by bmtheo** [comment]
Ok great

I'm closing this for now, the goal of making the lib customisable is to allow users to tweak behaviors as they like (your issue is a good example)

**Comment by spyro2000** [comment]
Ok, last try ;)
Maybe it would be a good idea to make this the default behavior so each message starts at the begin of a line? It's much more easy to read IHMO.

**Comment by bmtheo** [comment]
Thanks for your suggestion but I don't think changing the default behavior makes sense

**Comment by spyro2000** [comment]
I see, that's why I suggested to add a configura... - never mind. Thanks anyway ;)
