### ISSUE TITLE
Dependency on DatePipe causing circular dependency if the LOCALE_ID provider uses the logger.

### ISSUE THREAD

**Issue by acfaruk** [dbfannin/ngx-logger#293]
In our project we want to provide the LOCALE_ID by using a service. However this service and some of its dependencies use the logger. Meaning we end up with a circular dependency issue.

The question becomes if the library should depend on LOCALE_ID or not. Meaning currently the logger uses the project LOCALE_ID to format the date. It might make more sense to format uniformly, and not depending on the specific project?

It might be worth considering to switch to using the formatDate() method instead? Removing the dependency on LOCALE_ID and the pipe itself?

**Comment by bmtheo** [comment]
Ok DatePipe is now optional in version 5.0.8 :)

**Comment by acfaruk** [comment]
Thank you for the quick fix. 👍
