### ISSUE TITLE
Debug level does not work

### ISSUE THREAD

**Issue by kuceraf** [dbfannin/ngx-logger#3]
I  configure the logger like this:
`LoggerModule.forRoot({level: 'INFO'})`
but it still log the DEBUG, TRACE logs
eg.:
`this.logger.trace('aaaaa') `
goes to console. Even with level set to OFF the logs goes to console

**Comment by harikrishnan-u01** [comment]
Same here.

**Comment by dbfannin** [comment]
Hey, guys. Sorry for the late response. This has been fixed. pull down version 0.1.9.

**Comment by arnoldgamarram** [comment]
i use "ngx-logger": "^3.0.5", and debug message not print

**Comment by mxlpitelik** [comment]
Version 3.3.2 - and debug level didn`t works((((

`LoggerModule.forRoot({level: NgxLoggerLevel.TRACE}),`
or
`LoggerModule.forRoot({level: NgxLoggerLevel.DEBUG}),`

and result still same...

//didn`t show
`this.logger.debug('DEBUG!DEBUG!DEBUG!DEBUG!DEBUG!DEBUG!DEBUG!DEBUG!DEBUG!');`

//show
`this.logger.log('LOG!LOG!LOG!LOG!LOG!LOG!LOG!LOG!LOG!LOG!');`

But other flags (error, waring...etc) - is works!

**Comment by dbfannin** [comment]
@mxlpitelik, sounds like #88 might be the issue you're seeing. I would follow that issue.
