### ISSUE TITLE
issue with angular core dependency

### ISSUE THREAD

**Issue by summerbasehart** [dbfannin/ngx-logger#301]
Hello,

Trying to do a build in angular and I am getting some core dependency errors

Error: ./node_modules/ngx-logger/fesm2015/ngx-logger.mjs 900:58-80
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-logger/fesm2015/ngx-logger.mjs 899:58-80
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

I tried updating core and angular cli, but I still have the errors

**Comment by minademian** [comment]
Had the same error. I'm running Angular 11. Documentation says that the library supports 6+.

**Comment by bmtheo** [comment]
Thanks for sharing your solution

Documentation might not be up to date about versions that are supported

**Comment by bmtheo** [comment]
Documentation (on github, npmjs will be updated when next publish happens) is updated with a warning about this topic, ideally we should have a "matching table" for versions

**Comment by bmtheo** [comment]
Closing this issue, we are now using #308 to list all dependencies, once we have the full list it will be included in the doc
