### ISSUE TITLE
Can't use timeStampFormat because DatePipe is not provided

### ISSUE THREAD

**Issue by spyro2000** [dbfannin/ngx-logger#307]
I recently updated Angular 13->14 and ngx-logger 5.0.7 -> 5.0.11.
Since then, my custom date format isn't working anymore:

Error log:
`Can't use timeStampFormat because DatePipe is not provided. You need to provide DatePipe`

I couldn't find any information, how I need to provide this to ngx-logger unfortunately. Is there any code example available?

Here's my current logging config:

```
/**
 * Logging config for ngx logger
 */
export const logConfig = {
  // Configure log level depending on environment
  level: environment.logLevel,

  // We don't integrate server-side logging
  serverLogLevel: NgxLoggerLevel.OFF,

  // Simplified time format (default: ISO)
  timestampFormat: 'HH:mm:ss.SSS',

  // Support redirected to the source on click (depending on environment)
  enableSourceMaps: !environment.production,

} as INGXLoggerConfig
```

Many thanks in advance.

**Comment by bmtheo** [comment]
You need to provide DatePipe in your module where NGX logger is used, see documentation here https://angular.io/api/common/DatePipe

DatePipe import was removed from NGX logger because it's not mandatory

**Comment by spyro2000** [comment]
@bmtheo,

many thanks, but in this I would have to many dozens of modules. For the devs, it's not really obvious that they have to import a DatePipe to make the logging not break. If there isn't a possibility to import that globally, I'll just downgrade ngx-logger to make this work again.

But thanks anyway. :)

**Comment by bmtheo** [comment]
Yep I know, to avoid this you can create a module to automatically import NGXLogger and its specific dependencies

It will require to update all NGXLogger import but at least, you won't have any trouble at runtime
