### ISSUE TITLE
Using a theme while leaving the message text as is

### ISSUE THREAD

**Issue by slindenberg** [dbfannin/ngx-logger#31]
Hello, could you please give an option, to disable the color of the default text (message) in browser console?

**Comment by sam-lex** [comment]
are you perhaps looking for this? https://github.com/dbfannin/ngx-logger/issues/8

**Comment by dbfannin** [comment]
@slindenberg, was @sam-lex's comment helpful? can this issue be closed?

**Comment by slindenberg** [comment]
Sorry for my late response. What I was trying to say was, that some of our developers prefer a black console while other prefer a white one. The theme setting only fits one of those at a time. 

Would it be possible to leave the log messages text color as is (no coloring by the logger), so that the browser can swap the color when the background changes?

**Comment by sam-lex** [comment]
So what you asking is to leave the text coloring to its default...

I think an easy fix might be changing this:

```typescript
const defaultColor = this.options.enableDarkTheme ? 'white' : 'black';
console.log(`%c${this._timestamp()} [${Levels[level]}] %c${message}`, `color:${color1}`, `color:${defaultColor}`, ...additional);
```

into this:
```typescript
console.log(`%c${this._timestamp()} [${Levels[level]}]`, `color:${color1}`, message, ...additional);
```

This would make it unnecessary to set `enableDarkTheme`  
@dbfannin what do you think?

**Comment by sam-lex** [comment]
So I just tested it this morning. And works perfectly. But removing `enableDarkTheme` would be a "breaking change" for those who has already used it.

So I'm leaving it to you to make the appropriate changes...

**Comment by dbfannin** [comment]
@sam-lex, I like this. Can you send me a PR? I think the only thing to really keep in mind is to bump a major version, so that we don't break anyone using the dark theme.

**Comment by sam-lex** [comment]
@dbfannin sure. I'm new to versioning, by bumping a major version, you mean changing this: `0.2.9` to this: `1.2.9`?

**Comment by dbfannin** [comment]
@sam-lex, Check out my comments on the PR. Thanks!
