### ISSUE TITLE
Release Notes for 5.0?

### ISSUE THREAD

**Issue by DanielHabenicht** [dbfannin/ngx-logger#323]
Hi, on NPM there is a Version 5.0 but in this repository the most recent release is 4.2.1. 

Whats are the differences?

**Comment by bmtheo** [comment]
I didn't create the release on github

You can find the changelog here : https://github.com/dbfannin/ngx-logger/blob/master/CHANGELOG.md

**Comment by DanielHabenicht** [comment]
Ahh, alright. Thanks for taking the time. Somehow I didn't see it the first time. If you want to automate your release (with creating github release) I can highly recommned [semantic-release](https://github.com/semantic-release/semantic-release), I use it myself.
