### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by thethakuri** [dbfannin/ngx-logger#329]
I'm getting following error logging to the console (masked URL with XXX):

NGXLogger: Failed to log on server

OX {headers: qu, status: 502, statusText: 'Proxy Error', url: 'XXX', ok: false, …}
error
: 
"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>\n<hr>\n<address>Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.13 Server at XXX Port 443</address>\n</body></html>\n"
headers
: 
qu {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
: 
"Http failure response for XXX: 502 Proxy Error"
name
: 
"HttpErrorResponse"
ok
: 
false
status
: 
502
statusText
: 
"Proxy Error"

**Comment by bmtheo** [comment]
This is not related to the lib, the HTTP call is not going through because of some network issue

You should try to perform the HTTP call to see what's wrong

If you need further assistance, you should probably use community websites such as Stackoverflow

Closing issue
