### ISSUE TITLE
Support Angular 5

### ISSUE THREAD

**Issue by IsNull** [dbfannin/ngx-logger#33]
Basically allowing the 5.x.x branch in the peer dependencies should be enough.

**Comment by dbfannin** [comment]
@IsNull, would you like to send me a PR for this? Should be straightforward enough.

**Comment by IsNull** [comment]
Yes I can do this. I already used the current version of this lib with Angular 5 and it appears to work well - except for the peer dependency warning.

**Comment by dbfannin** [comment]
Thanks!

**Comment by IsNull** [comment]
See PR  #35

**Comment by davidkarlsen** [comment]
Any chance of merging and releasing this?

**Comment by dbfannin** [comment]
@davidkarlsen, this has been merged and released in version 2.0.0
