### ISSUE TITLE
How to implement custom server request handling?

### ISSUE THREAD

**Issue by sakonn** [dbfannin/ngx-logger#335]
Hello,
thanks for the nice project. We have an ionic app built with angular and we would like to implement a collection of logs there. The crucial requirement for us is the reliability of log delivery to the server where logs would be stored and analyzed. If I understand the code correctly when the request to the backend api fails there is just a `console.error` statement without any further logic. I have checked [this file](https://github.com/dbfannin/ngx-logger/blob/master/src/lib/server/server.service.ts#L220). 
My idea is to incorporate a custom request error handler which would store failed requests temporarily (maybe local storage) and then reupload them later. What would be the best way to implement it?

**Comment by bmtheo** [comment]
You can do this by overriding server.service.ts, this is not super convenient but it works

See example in this discussion we had on our discord :
You could override server.service logOnServer and add a catcherror operator
Overriding example (writing from phone right now so syntax is not ok) :
```
override logOnServer(
    url: string,
    logContent: any,
    options: {
      headers?: HttpHeaders;
      reportProgress?: boolean;
      params?: HttpParams;
      responseType?: 'arraybuffer' | 'blob' | 'json' | 'text';
      withCredentials?: boolean;
    },
  ): Observable<any> {
  Return Super.logonserver(...).pipe(catchError(err => ...));
}
```

**Comment by Aleksander-Dorkov** [comment]
@bmtheo 
Could you please post what you answered here in NPM dcoumentation.
https://www.npmjs.com/package/ngx-logger

**Comment by sakonn** [comment]
Hello, thanks for the answer. I ended up with a custom implementation but your answer may help someone else in the future.
So, the issue can be closed.
