### ISSUE TITLE
Logger doesn't work properly on IE11

### ISSUE THREAD

**Issue by harikrishnan-u01** [dbfannin/ngx-logger#4]
Logger doesn't work properly on IE11.

In IE11 its printing as:

![image](https://user-images.githubusercontent.com/10159959/28691958-b1ba42a4-72ec-11e7-84ed-bfe46733e0d0.png)

In Chrome its printing as:

![image](https://user-images.githubusercontent.com/10159959/28691985-c6d92ab0-72ec-11e7-811c-d69208326ae9.png)

Thanks,
Hari

**Comment by dbfannin** [comment]
@harikrishnan-u01, I have modified the logger to work for IE. it will use the web browser console.log, console.info, console.warn and console.error. Hopefully this works for you. The change is in version 0.1.13.
