### ISSUE TITLE
Angular 5 cyclic dependency

### ISSUE THREAD

**Issue by calamarico** [dbfannin/ngx-logger#40]
I'm trying to import the module in a angular 5.2.2 app, but when I import in the coreModule the ngx-logger, I have the next error:
```
Uncaught Error: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
```
I saw the @IsNull PR: https://github.com/dbfannin/ngx-logger/pull/35 for angular 5 compatibility, but I want to ask if you have imported succesfully this module into an angular >5.2.
Regards!

**Comment by calamarico** [comment]
@brandPittCode Hi!, yes, take a look to [this post](https://stackoverflow.com/questions/50354895/cant-show-a-material-snackbar-for-the-backend-errors-using-custom-errorhandler/50356410#50356410) and see my answer, because both problems are the same, you need yo use Injector to avoid the cyclic problem

**Comment by brandPittCode** [comment]
Thank you @calamarico .  I had the same problem with Cannot instantiate cyclic dependency! A HttpClient ("[ERROR ->]") 
in a class that implements HttpInterceptor. I'm working with ionic and Angular 4. I used the same approach of your post and it works now.

**Comment by calamarico** [comment]
I'm glad to hear that!!. You can upvote the answer if you found it useful XD
