### ISSUE TITLE
Use AppConfig in AppModule

### ISSUE THREAD

**Issue by maciej-karpus** [dbfannin/ngx-logger#41]
Hi,
regarding to the instruction of passing config to logger:
```
@NgModule({
  declarations: [AppComponent, ...],
  imports: [LoggerModule.forRoot({serverLoggingUrl: '/api/logs', level: NgxLoggerLevel.DEBUG, serverLogLevel: NgxLoggerLevel.ERROR}), ...],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

Could you give me some advice how to set serverLoggingUrl using value from my AppConfig?

**Comment by dbfannin** [comment]
@maciej-karpus, I'm not sure I quite understand the question. LoggerModule.forRoot() takes the LoggerConfig as in input parameter. In your comment you have the section which shows how to set the serverLoggingUrl. So you would pass in an object that has serverLoggingUrl set to the path for your logs to be sent. 

Is AppConfig something your application is providing? Please provide more details.

**Comment by maciej-karpus** [comment]
@dbfannin Sorry to bother you, I'm ok now. I had a weird concept of AppConfig, I changed it and have no problem anymore. The issue was totally not connected with your library, which is great btw. Congratulations!
