### ISSUE TITLE
Error: Converting circular structure to JSON (Failed to Log on Server)

### ISSUE THREAD

**Issue by th3n3wguy** [dbfannin/ngx-logger#42]
Whenever the server-logging is enabled, there is not a catch functionality that allows for the `message` and `additional ` to be parsed to a string before the `POST` request is sent. This is causing an issue where the UI will stop functioning and crash the Angular application.

Here is the line of code where the failure starts: https://github.com/dbfannin/ngx-logger/blob/master/src/logger.service.ts#L88

If I have a chance, I will attempt to submit a pull request. If not, then the only thing that needs to happen is for the `message` and each value of the `additional` need to be wrapped in a `try / catch` block and then the strings sent. Otherwise, just log to the console.

**Comment by dbfannin** [comment]
Hey! thanks for identifying this issue. Please send me a PR and I'll get the changes in!

**Comment by th3n3wguy** [comment]
@dbfannin => Can you please take a look at the pull request I have submitted for this as soon as you can? I need to get these changes in downstream projects as soon as possible. Thanks!

**Comment by dbfannin** [comment]
@th3n3wguy, since the PR has been merged. I'm going to close this issue out. Thanks again.
