### ISSUE TITLE
Allow custom adapters for server logging

### ISSUE THREAD

**Issue by jasekiw** [dbfannin/ngx-logger#44]
Instead of providing a serverLoggingUrl I would like to be able to add adapters to allow for custom storing implementations. This could allow for log queuing when offline, and authentication with the server and include user information.

This section would have to be changed to allow for a custom adapter.

https://github.com/dbfannin/ngx-logger/blob/b70df79a1867e6f98d5de0fe9d69925f274182d1/src/logger.service.ts#L102-L116

This code will need to be moved into the prepackaged adapter for backwards compatibility.

Add a method like setServerAdapter to swap it out at any time or it can be provided in the LoggerModule.forRoot configuration object. Possibly lamda expressions or interface implementation or both.

I have written some code to allow this.  I can submit a PR for this if this is the way to go.

Side Note: I noticed that I could not run the unit tests and that the build chain for that is seemingly broken.

@th3n3wguy @dbfannin let me know what you think.

Thanks!

**Comment by dbfannin** [comment]
@jasekiw, I agree, we should have a better way of sending logs to the backend. Instead of supporting different adapters or overriding headers, and all the things that go into secure vs nonsecure HTTP requests, I think it would be easier and more customizable to allow users to define their own HTTP Service and provide it in the app.

if you look at the break apart service PR, (#50), you'll see we've pulling the http method out of the logger service. Doing this should allow us to override that service with our own service that we could write up however we want. Your thoughts on this?

**Comment by jasekiw** [comment]
@dbfannin That was exactly my thought. By custom adapter I meant defining their own implementation. I will take a look at the pull request and see if I can add any input. I couldn't get tests on the repository running. Is that an issue I should open or is it something I'm missing?

**Comment by dbfannin** [comment]
@jasekiw, tests are something that we plan on improving in the very near future. Unfortunately, we don't have any tests at the moment.

Also, this change doesn't yet support providing your own http service, but this should now allow us to do that with relative ease.

Any input you have on the PR would be greatly appreciated! Also, if you would like to contribute (by either working on the custom http service, or adding some tests), we're always looking for more contributors. Thanks!

**Comment by jasekiw** [comment]
@dbfannin I definitely want to contribute more open source work. This week is my spring break and I will have some hours to put forth pull requests.

**Comment by dbfannin** [comment]
Sounds great! Thanks!

**Comment by camstuart** [comment]
I'm keen to see the ability to modify the server's payload. I want to use stackdriver to capture logs. How did you with a building the PR @jasekiw ? let me if you ran out of time, I may be able to help

**Comment by dbfannin** [comment]
this use case should be handled by #85. closing issue.
