### ISSUE TITLE
Explain how to use in tests

### ISSUE THREAD

**Issue by kathomas921** [dbfannin/ngx-logger#51]
ng test keeps failing because of a null injection error, ie:
```
Error: StaticInjectorError(DynamicTestModule)[UserService -> NGXLogger]: 
  StaticInjectorError(Platform: core)[UserService -> NGXLogger]: 
    NullInjectorError: No provider for NGXLogger!
```
Please explain what to include in tests files to eliminate this error. It works fine outside the testing framework.

**Comment by dbfannin** [comment]
@kathomas921, sounds like you're not providing the logger when configuring your testing module. Can you verify that you are injecting it? There also is also mock class for the logger. Try adding `{provide: NGXLogger, useCLass: NGXLoggerMock}` to your testing module providers (see below).

```
     TestBed.configureTestingModule({
       providers: [
         {provide: NGXLogger, useCLass: NGXLoggerMock},
         ...
       ],
       ...
     });
```

**Comment by dbfannin** [comment]
@kathomas921, did this solve your issue? if so, I will close this out.

**Comment by th3n3wguy** [comment]
@dbfannin => Your way is exactly how it works in my application right now, but I do believe that we should probably update the `README.md` file to include this information for future developers.

**Comment by dbfannin** [comment]
@th3n3wguy, good feedback. I'll add it to the PR you've been reviewing for me.

**Comment by kathomas921** [comment]
Yes, that fixed it for me, thanks!

**Comment by atecey** [comment]
I get "Failed: Cannot read property 'debug' of undefined" when using the mock provider when testing a service. Not sure what I'm missing but more detail/examples around using this in tests would be good

My setup is 

```
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpClientTestingModule
      ],
      providers: [
        MyService,
        {
          provide: NGXLogger, useCLass: NGXLoggerMock
        }
      ]
    });
  }));
```

**Comment by dbfannin** [comment]
@atecey, that's the correct way to use the mock service for testing. Can you provide more details on what version of the logger you're using?

**Comment by atecey** [comment]
The very latest version 2.2.1. Just pulled from npm today

**Comment by dbfannin** [comment]
@atecey, I just noticed there is a typo in your providing of the mock. `useCLass` should be `useClass`. That should fix your issue. there was a typo in the readme, and that probably messed you up. I've updated the readme for future devs. Hope this helps!

**Comment by atecey** [comment]
Good spot that was it thanks
