### ISSUE TITLE
Latest npm version is 2.0.7 but master branch only has 2.0.2 in package.json

### ISSUE THREAD

**Issue by jasekiw** [dbfannin/ngx-logger#52]
There seems to be a version mismatch. @dbfannin can you confirm?

**Comment by dbfannin** [comment]
@jasekiw, I just double checked and everything is fully up to date at 2.0.7. Where are you seeing 2.0.2? if it's locally on your machine, make sure you're pulling from origin/master and not a local branch.

**Comment by jasekiw** [comment]
@dbfannin Yeah I just realized it I was pulling from my fork and not from the main repo. Sorry for the inconvenience.

**Comment by dbfannin** [comment]
No problem! I actually just merged the PR that was out there. so pull one more time to make sure you're fully up to date at 2.1.0

**Comment by jasekiw** [comment]
@dbfannin Just pulled that version :)
