### ISSUE TITLE
Cannot log raw objects

### ISSUE THREAD

**Issue by iamthechad** [dbfannin/ngx-logger#54]
Per #12, it looks like I should be able to log arbitrary objects and inspect them in the same manner as using `console.log`. However, I am constantly running into `The additional[0] value could not be parsed using JSON.stringify()` and have to resort to `console.log` to see the actual object I'm interested in. I don't see any code path that doesn't try to transform the object.

**Comment by dbfannin** [comment]
Hey @iamthechad! You definitely should be able to log arbitrary objects to the browser console. We do however, want to stringify the object (or at least validate it can be parsed) before sending the HTTP request. 

#55 should fix this issue. Thanks for the feedback!

**Comment by dbfannin** [comment]
@iamthechad, you should now be able to log objects directly to the console with ngx-logger@2.1.1. Thanks!
