### ISSUE TITLE
source maps/webpack-internal

### ISSUE THREAD

**Issue by jkossis** [dbfannin/ngx-logger#58]
When logging errors with ngx-logger, I am getting references to webpack-internal resources, rather than the mapped source files (seen when logging with basic console). See the attached image:

![capture](https://user-images.githubusercontent.com/1247832/38823874-951e423c-4175-11e8-8433-1556293d9bbc.PNG)

Is this expected, and if so, is there a way to use ngx-logger and still maintain the source maps links?

**Comment by jkossis** [comment]
If you take a look at the two screenshots I provided, you'll notice the discrepancy.

The first one, which is using ngx-logger, links to webpack-internal files. The second one, which is using standard console, links to the approrpiate source maps (webpack, non internal).

Is there a way for ngx-logger to link to the source maps, similar to the way in which console does?

Let me know if this isn't clear either. I am sorry for the confusion.

**Comment by dbfannin** [comment]
@jkossis, I'm assuming this has been resolved and closing the issue. let me know if you're still having issues.

**Comment by jkossis** [comment]
@dbfannin indeed, this resolved the issue. I really appreciate you looking into it!

**Comment by dbfannin** [comment]
Excellent!

**Comment by zeevkatz** [comment]
Faced the same issue with `ngx-logger@3.3.2` :(

**Comment by dbfannin** [comment]
@zeevkatz, #69 is the open ticket where this is being tracked. It's due to some build changes in Angular 6.

**Comment by dungtran98** [comment]
hi @dbfannin  @jkossis . How do i change from ./src/app/app.module to webpack:///.src/app/app.module?
![image](https://user-images.githubusercontent.com/51997678/129512450-64613847-5dd1-481a-a4b8-1b5dc3152d01.png)
