### ISSUE TITLE
Module not found: Error: Can't resolve 'lodash'

### ISSUE THREAD

**Issue by KeithPepin-CyG** [dbfannin/ngx-logger#6]
After a fresh install of v0.1.7 I get the following error after including ngx-logger in my app.module.js providers (I'm using Angular 4):

```
ERROR in ./~/ngx-logger/index.js
Module not found: Error: Can't resolve 'lodash' in '/Users/keithpepin/git-repos/cyglass-app/node_modules/ngx-logger'
 @ ./~/ngx-logger/index.js 8:0-35 9:0-28
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
```

moment.js is the only dependency listed for the ngx-logger, everything else is dev dependencies.

**Comment by dbfannin** [comment]
I have removed lodash as a dependency from the logger. You shouldn't have this problem any more (version 0.1.12)
