### ISSUE TITLE
.net core 2 with ngx-logger - class helper

### ISSUE THREAD

**Issue by Kaidanov** [dbfannin/ngx-logger#64]
Just wanted to help others.Please mark this issue as helper labeled.- 

Tried to use it. 
Arrived to server .net core 2 with null.

So I've created a helper class.Automatic creator here-  https://app.quicktype.io/#l=cs&r=json2csharp

` // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using ApiApp.NetworkModels.Classify;
    //
    //    var logClient = LogClient.FromJson(jsonString);

    //{"message":"test",
    //"additional":[],"level":3,
    //"timestamp":"2018-05-01T07:37:18.591Z",
    //"fileName":"classify.component.ts","lineNumber":"52"}
`

`namespace AbiApp
{
   

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using J = Newtonsoft.Json.JsonPropertyAttribute;
    using N = Newtonsoft.Json.NullValueHandling;

    public partial class LogClient
    {
        [J("message", NullValueHandling = N.Ignore)]    public string Message { get; set; }           
        [J("additional", NullValueHandling = N.Ignore)] public List<object> Additional { get; set; }  
        [J("level", NullValueHandling = N.Ignore)]      public long? Level { get; set; }              
        [J("timestamp", NullValueHandling = N.Ignore)]  public DateTimeOffset? Timestamp { get; set; }
        [J("fileName", NullValueHandling = N.Ignore)]   public string FileName { get; set; }          
        [J("lineNumber", NullValueHandling = N.Ignore)] public string LineNumber { get; set; }        
    }

    public partial class LogClient
    {
        public static LogClient FromJson(string json) => JsonConvert.DeserializeObject<LogClient>(json, LogClientConverter.Settings);
    }

    public static class LogClientSerialize
    {
        public static string ToJson(this LogClient self) => JsonConvert.SerializeObject(self, LogClientConverter.Settings);
    }

    internal static class LogClientConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = { 
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

`

And in the controller i have a receiving method

` [HttpPost("clientlogdata")]
        public  Task<IActionResult> ClientLogData([FromBody] LogClient LogClient)
        {
            Console.Write(LogClient.ToJson());
            return null;
        }`

**Comment by dbfannin** [comment]
@Kaidanov, thanks for sharing!
