### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by kkrishnakv** [dbfannin/ngx-logger#65]
Getting error will trying to log the information to server with multiple arguments. It is working fine with single argument

export class GlobalErrorHandler implements ErrorHandler {
    constructor(private logger: NGXLogger) { }
    public handleError(error) {
        this.logger.error('error', error);
        throw error;
    }
}
 LoggerModule.forRoot({
             serverLoggingUrl: './app-api/api',
              serverLogLevel: NgxLoggerLevel.ERROR,
               level: NgxLoggerLevel.TRACE }),

**Comment by dbfannin** [comment]
@kkrishnakv, what version of the logger are you using?

**Comment by dbfannin** [comment]
@kkrishnakv, Are you still having an issue?

**Comment by dbfannin** [comment]
@kkrishnakv, since I haven't heard back from you, I'm closing this issue. Please re-open it if you're still having this issue.
