### ISSUE TITLE
[Feature Request] Allow for custom Date formatters

### ISSUE THREAD

**Issue by danielr1996** [dbfannin/ngx-logger#66]
# IS
ngx-logger formats the logging date as ISO String (2018-05-25T05:22:04.243Z)

# SHOULD
it would be nice if you could provide custom date formats, because the iso Date is very long and often you don't care about the date and milli seconds, so 05:22:04 would be enough

**Comment by dbfannin** [comment]
@danielr1996, formatting the date string really hasn't been a feature that anyone has requested up until now. If you're interested in making the changes and sending in a PR, I'll take a look at it!

**Comment by mbeckenbach** [comment]
@dbfannin I request that too. :-)

**Comment by dbfannin** [comment]
Is this still a feature that would be useful?

**Comment by dbfannin** [comment]
It's been 4 weeks and I haven't heard a response. I'm going to close the issue. If it is still something desired, please open a new issue.
