### ISSUE TITLE
build is failing when trying to implement ngx-logger in my application

### ISSUE THREAD

**Issue by ahsanahmad22** [dbfannin/ngx-logger#67]
Hi, 

**When I build my module after implementing ngx-logger, I am getting below error**-
[INFO] ?[31mFatal error: Error on fetch for npm:rxjs at file:///F:/IdeaProjects/GCU_Project/git_projectes/sprint98/gcu-sis.sis-web/node_modules/rxjs
[INFO]  Loading npm:ngx-logger/bundles/ngx-logger.umd.js
[INFO]  Loading js/app.module.ts
[INFO]  Loading main.ts
[INFO]  EISDIR: illegal operation on a directory, read?[39m

**Below are changes I made in app.module.ts file** -
import { LoggerModule, NgxLoggerLevel } from 'ngx-logger'; and added in imports  below line -
LoggerModule.forRoot({serverLoggingUrl: '/api/logs', level: NgxLoggerLevel.DEBUG, serverLogLevel: NgxLoggerLevel.ERROR})

**below is my app.component.ts file** -

import { Component, Inject} from '@angular/core';
import { UpgradeModule } from "@angular/upgrade/static";
import { Router } from '@angular/router';
import { CookieService } from 'ngx-cookie-service';
import { ReleaseConfigService } from './release.config.service';
//import './scholarships/athletics/app.downgrade';
import { Component } from '@angular/core';
import { NGXLogger } from 'ngx-logger';

export function setUpLocationSync(ngUpgrade: UpgradeModule) {

    if (!ngUpgrade.$injector) {
        throw new Error('RouterUpgradeInitializer can be used only after UpgradeModule.bootstrap has been called. ' +
            'Remove RouterUpgradeInitializer and call setUpLocationSync after UpgradeModule.bootstrap.');
    }

    const router: Router = ngUpgrade.injector.get(Router);
    const url = document.createElement('a');
    let currentUrl = router.url + '?';
    router.routeReuseStrategy.shouldReuseRoute = function () { return false; };
    ngUpgrade.$injector.get('$rootScope')
        .$on('$locationChangeStart', (_: any, next: string, __: string) => {
            url.href = next;
            router.navigateByUrl(currentUrl).then(() => {
                router.navigated = false;
                router.navigate([url.hash.substr(1)]);
            });
        });
}
@Component({
  selector: 'app-root',
  templateUrl: 'js/app.component.html',
  providers: [NGXLogger]
})
export class AppComponent {
    constructor(private upgrade: UpgradeModule, private cookieService: CookieService, private releaseConfigService: ReleaseConfigService,
        private logger: NGXLogger ) {
            this.logger.debug('Your log message goes here');
            this.logger.debug('Multiple', 'Argument', 'support');
}
    ngOnInit() {
        this.upgrade.bootstrap(document.body, ['sisApp'], { strictDi: true });
        setUpLocationSync(this.upgrade);
    }
}

**I added dependency in systemjs.config.js file is** -

'ngx-logger' : 'npm:ngx-logger/bundles/ngx-logger.umd.js',

complete code is -
System.config({
   transpiler: 'ts',
   typescriptOptions: {
       // Copy of compiler options in standard tsconfig.json
       "target": "es5",
       "module": "commonjs",
       "moduleResolution": "node",
       "sourceMap": true,
       "emitDecoratorMetadata": true,
       "experimentalDecorators": true,
       "noImplicitAny": true,
       "suppressImplicitAnyIndexErrors": true
   },
   meta: {
       'typescript': {
           "exports": "ts"
       },
       '*.json': { "loader": "json" }
    },
   paths: {
       // paths serve as alias
       'npm:': 'node_modules/'
    },
   // map tells the System loader where to look for things
   map: {
       // our app is within the app folder
       'app': 'js',
       // angular bundles
       '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
       '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
       '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
       '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
       '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
       '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
       '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
       '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
       '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
       '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',
       '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
       'tslib': 'npm:tslib/tslib.js',
        'ngx-logger' : 'npm:ngx-logger/bundles/ngx-logger.umd.js',
       // other libraries
       'rxjs':                      'npm:rxjs',
       'ngx-cookie-service':        'npm:ngx-cookie-service/cookie-service/cookie.service.js',
       'ts':                        'npm:plugin-typescript/lib',
       'typescript':                'npm:typescript/lib/typescript.js',
       'angular-scholarship-seed':     'npm:angular-scholarship-seed/bundles/angular-scholarship-seed.umd.js',
       'angular-dpa-seed':     'npm:angular-dpa-seed/bundles/angular-dpa-seed.umd.js',
       'ngx-bootstrap': 'npm:ngx-bootstrap/bundles/ngx-bootstrap.umd.js',
       'angular2-multiselect-dropdown': 'npm:angular2-multiselect-dropdown/index.umd.js',
       'file-saver': 'npm:file-saver'
   },
   // packages tells the System loader how to load when no filename and/or no extension
   packages: {
       app: {
           main: './main.ts',
           defaultExtension: 'ts'
       },
       rxjs: {
           defaultExtension: 'js'
       },
       ts: {
           main: './plugin.js',
           defaultExtension: 'js'
       }
   }
})

I am using rxjs version - 5.2.6
**below are dependencies I am using in package.json -**
"dependencies": {
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/platform-server": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0",
    "angular-dpa-seed": "file:angular-dpa-seed-0.0.0.tgz",
    "angular-scholarship-seed": "file:angular-scholarship-seed-0.0.0.tgz",
    "angular2-multiselect-dropdown": "2.5.0",
    "babel-core": "^6.26.0",
    "file-saver": "^1.3.3",
    "grunt-clearcache": "0.0.4",
    "ngx-bootstrap": "2.0.2",
    "ngx-cookie-service": "1.0.10",
    "ngx-logger": "^3.0.0-rc1",
    "node-gyp": "^3.6.2",
    "plugin-typescript": "4.0.10",
    "rxjs": "^5.5.2",
    "rxjs-system-bundle": "^5.5.2",
    "systemjs-builder": "0.15",
    "typescript": "2.6.2"
  }

**Comment by dbfannin** [comment]
@ahsanahmad22, a couple things I've noticed. 

1. this issue doesn't have anything to do with the logger itself. `Error on fetch for npm:rxjs`. This is an issue trying to "fetch" rxjs.
2. You're using `ngx-logger@3.0.0-rc1` which is built on angular 6, but your project is running angular 5. Angular is backwards compatible, but not forwards compatible with packages, meaning you could use Angular 4 package, but not angular 6. 

Try to pull in a previous version of the logger, and it might solve your issue. The last version published with angular 5 is `ngx-logger@2.2.4`

**Comment by ahsanahmad22** [comment]
Thanks @dbfannin ,

Issue was because of incorrect ngx-logger version. Issue is resolved in my local.

**Comment by eivanphils** [comment]
Hi, I had the same problem, but I can solve it. I install this version "ngx-logger": "^4.3.3"

It's necessary to add HttpClientModule into app module. Like this:


![image](https://user-images.githubusercontent.com/1909869/148953364-c04e47ca-fdb6-4696-a7ef-96a7e5869e4d.png)
