### ISSUE TITLE
Is there a configurable ajax appender ? 

### ISSUE THREAD

**Issue by NewbieAngular** [dbfannin/ngx-logger#68]
I would like to send log messages to the server in batches by an ajax call. Is that possible? If so, how?

**Comment by dbfannin** [comment]
@NewbieAngular, #62 is supposed to solve this issue, allow you to extend the functionality, but it is not currently supported. I'll try to put some time in on this in the near future. keep an eye out!

**Comment by dbfannin** [comment]
@NewbieAngular, #62 has been abandoned and #85 should now solve this use case. disable server logging and handle your batch requests as needed. Sorry it's taken so long.
