### ISSUE TITLE
Update config requires all config properties to be supplied

### ISSUE THREAD

**Issue by slubowsky** [dbfannin/ngx-logger#70]
Updating logger config with only a level blows away earlier serverLogLevel and/or serverLoggingUrl settings. Any not provided value should not cause the current setting for that value to change.

**Comment by slubowsky** [comment]
@dbfannin That would work.
I guess "updateConfig" to me sounds like a partial update as opposed to "setConfig" which would clearly mean a full update. I was also fooled by the fact that serverLogLevel and serverLoggingUrl are optional in LoggerConfig. To do what I want though, level would also have to be optional.

**Comment by dbfannin** [comment]
@slubowsky, There is now a method on the logger service `getConfigSnapshot()` which returns the current config. You can then update the values you wish to update, and set the config. I hope this helps! This is available in `ngx-logger@3.0.1`.

**Comment by slubowsky** [comment]
@dbfannin Thanks, that works.
One thing you might want to change though. Not sure if its a problem with getConfigSnapshot, updateConfig, or both, but if you modify the config object through your reference to it, it affects the logger. See example below. Without clone, my app stops logging to server!

```
public setLogLevels(logLevels: LogLevels) {
    const config: LoggerConfig = this.logger.getConfigSnapshot();
    if (logLevels.level !== undefined) {
        config.level = logLevels.level;
    }
    if (logLevels.serverLogLevel !== undefined) {
        config.serverLogLevel = logLevels.serverLogLevel;
    }
    this.logger.updateConfig(config);

    // OUCH - apparently this object is shared live!!!!!!!
    // until fixed clone it first
    const clone = JSON.parse(JSON.stringify(config));
    delete clone.serverLoggingUrl;

     this._logLevels.next(clone);
     this.localStorageService.setObject(this.LOCAL_STORAGE_KEY, clone);
}
```

**Comment by dbfannin** [comment]
yikes! good catch. `ngx-logger@3.0.2` clones the config so this doesn't happen!

**Comment by slubowsky** [comment]
@dbfannin Thanks but still no good. Your clone is empty!  :cry:  (Object.keys(cloneConfig) is empty. Its only typescript that knows of the type...)

**Comment by dbfannin** [comment]
oh man. rough day. one more try `3.0.3`?

**Comment by slubowsky** [comment]
@dbfannin Not seeing a 3.0.3 yet. Should I be?

**Comment by dbfannin** [comment]
can you check again?

**Comment by slubowsky** [comment]
@dbfannin I see 3.0.3 now but still see the issue. Looks like the same problem exists on the way in with updateConfig. Changing the object I passed in at a later time will apparently affect the logger.

**Comment by slubowsky** [comment]
Yes. I believe that get config is now working correctly and this is a different problem in that later modifying the object that was previously passed into updateConfig will cause logger config to change

**Comment by slubowsky** [comment]
Yes. 3.0.4 works as expected. Thank you.
