### ISSUE TITLE
Create a demo app

### ISSUE THREAD

**Issue by bniedermeyer** [dbfannin/ngx-logger#72]
I noticed that the Angular CLI and ng-packagr are now being used for the build system. Since that provides access to the Angular CLI workspaces we could add an example app that uses ngx-logger to not only give good usage examples but help troubleshoot things locally without needing to mess around with `npm link`. 

I'd be happy to throw together a PR over the next couple weeks but wanted to put the idea out for feedback first.

**Comment by dbfannin** [comment]
@bniedermeyer, I think that's a great idea! shoot me a PR and I'll take a look! Thank you!

**Comment by bniedermeyer** [comment]
I got sidetracked by some work issues so I'm still working on this. Hope to have it in a PR in the next week or so
