### ISSUE TITLE
how can we show error on terminal or in any log file?

### ISSUE THREAD

**Issue by madhuri03** [dbfannin/ngx-logger#73]

**Comment by dbfannin** [comment]
@madhuri03, I'm not sure I understand the question. If you are wondering how to implement the logger, please checkout the readme.

**Comment by blackbeario** [comment]
@dbfannin I'm not sure I am expressing the same question as @madhuri03, but it seems related. I have installed ngx-logger and it is working great via the console. But I am having issues writing to the server. I have the logs path set as `serverLoggingUrl: '/logs'` and I have created a directory. 

My specific question is basic. Does ngx-logger create new files in that directory or how should it work? The readme simply says:
> If serverLogginUrl exists, NGX Logger will attempt to POST that log to the server.

I think further explanation for new angular devs like myself would be helpful.

**Comment by blackbeario** [comment]
I think I have found the error of my ways. I am using Loopback API and created a model called 'log' with an endpoint at localhost:3000/api/logs. Using that endpoint I am able to reach the URL with the logger serverLoggingUrl. Now I just need to fix my permissions and required properties issues.

This typeof thing may be obvious most devs, but for newbies like me a pointer in the readme could be helpful for sure.

**Comment by dbfannin** [comment]
@blackbeario, it seems you figured out the issue? the POST is referring to an HTTP POST and there must be a back end set up to accept the HTTP request. I'll look at updating the readme, so that it is more clear.

If this issue is resolved, can you please close it?

**Comment by blackbeario** [comment]
Yes @dbfannin, for me personally, this was just a lack of understanding of the requirements. A simple notice stating it requires a back-end endpoint may be obvious, but could still be helpful. I didn't open this issue, and unfortunately I do not see a way to close it. Otherwise I'd be happy to.

**Comment by dbfannin** [comment]
@blackbeario, I can close the issue after we get everything resolved for you. It appears that @madhuri03 has removed his request.

The 422 status is from your server that is receiving the the request. (whatever app that is bound to localhost:3000 and listening for a POST request on /api/logs). You should look there to make sure it's supports a JSON payload. This doesn't appear to have anything to do with the logger, or the Angular code. 

I hope this helps!

**Comment by blackbeario** [comment]
Thanks @dbfannin. Yes, Loopback supports JSON. If I enter the same data post manually in JSON format in the Loopback explorer it successfully returns a 200 response code and saves to mongodb.

Anyway, that's all on my end. I'll figure it out. Thanks for this project!!

**Comment by blackbeario** [comment]
@dbfannin I finally see what's going on with my issue. NGX-Logger is sending a payload like this:
```
additional: []
fileName: "user-user-module.js"
level: 3
lineNumber: "624"
message: "{ "model": "user",↵  "method": "log",↵  "message": "testuser44 created",  "userID": "5b2090c8f0e27c26d38b7d5e"}"
timestamp: "2018-07-23T15:59:47.243Z"
```
My API is expecting `model`, `method`, `message`, and `userID` as individual required properties, but logger.log() is merging them all into `message` as you can see above. So  it's failing because the required properties aren't being sent. This is the actual error:

```
message: "The `log` instance is not valid. Details: `model` can't be blank (value: undefined); `method` can't be blank (value: undefined)."
```

So how should I format my post differently to accommodate the needed arguments? Again, this is how I'm attempting it now:
```
 this.logger.log({
   model: 'user',
   method: 'log',
   message: item.username + " created",
   userID: this.currentUserId()
});
```

**Comment by blackbeario** [comment]
Ok, so with that method, I am still going to need to conform my `log` API model to those properties, e.g. `additional`, `filename`, `level`, `lineNumber`. Those are helpful properties to keep track of in addition to the other properties I had originally planned. Just out of curiosity though, if I create a custom logger with it's own config, am I able to alter those default properties?

**Comment by blackbeario** [comment]
@dbfannin I successfully posted to the API endpoint using the properties set by logger.log(). I think my efforts here would be good documentation for the layman attempting to replicate this process. Thanks again for your help. I would appreciate an answer to the previous comment, but feel free to close this ticket.

**Comment by dbfannin** [comment]
@blackbeario, #72 is to set up a demo app within the project that shows how to implement the logger and the features of the logger. So I believe this will be covered in it. Glad to hear you got it working! Closing this issue out!
