### ISSUE TITLE
How to I use this library to send errors also to Sentry.io?

### ISSUE THREAD

**Issue by idanb11** [dbfannin/ngx-logger#78]

**Comment by dbfannin** [comment]
@idanb11, I've not used Sentry.io before. I would watch the `Server Side Logging` section of the docs. Or watch for the update to support the custom logging notification service. If you get ngx-logger to send errors to Sentry.IO, it would be nice to have that documented for anyone else in the future who is trying to do the same thing.

**Comment by dbfannin** [comment]
@idanb11 #85 or #86 should help with your sentry.io issue. If you just have to point to a specific URL, and set custom authorization headers, then #86 should do, if you have to do some other customizations, then I would disable server logging in the config, and register a custom log monitor to handle passing your logs to Sentry.io.

I hope this helps!
