### ISSUE TITLE
How to use it into ErrorInterceptor class ?

### ISSUE THREAD

**Issue by pairmix** [dbfannin/ngx-logger#79]
ERROR Error: StaticInjectorError(AppModule)[InjectionToken HTTP_INTERCEPTORS -> NGXLogger]: 
  StaticInjectorError(Platform: core)[InjectionToken HTTP_INTERCEPTORS -> NGXLogger]: 
    NullInjectorError: No provider for NGXLogger!

**Comment by dbfannin** [comment]
not where exactly the issue is, but the error is that NGXLogger is not provided. Make sure you're importing the `LoggerModule` into the module that is trying to use the logger. good luck
