### ISSUE TITLE
customise the log color, which is hard coded to black.

### ISSUE THREAD

**Issue by jimmymain** [dbfannin/ngx-logger#8]
Hi,

This line of [code](https://github.com/dbfannin/ngx-logger/blob/297037da98771c729dcdc862726eb866fe720c58/src/logger.service.ts#L118)

```
console.log(`%c${moment.utc().format()} [${level}] %c${message}`, `color:${color1}`, 'color:black');
```
has the console color set to black.
can you add configuration for this please, I am using a "dark" theme, therefore black doesn't work particularly well for me.

**Comment by dbfannin** [comment]
@jimmymain,

I've added a configuration property **enableDarkTheme** which will make the default color white instead of black in version 0.1.15. Hope this solves your problem. Thanks for using the logger!
