### ISSUE TITLE
Server logging - Additional data not sent

### ISSUE THREAD

**Issue by stephanie-b1n3t** [dbfannin/ngx-logger#81]
Server logging is very useful but it just send `message` parameter and doesn't send `additional` parameters from logging methods.

Could it be possible to enhance this ? 

**Example :** 

`ngxLogger.error('My context - error code=', error.code );`

Message received: `My context - error code=`
Message expected: `My context - error code=404` 

Nervertheless thanks for this great logger.

**Comment by dbfannin** [comment]
@stephanie-b1n3t, the logger should be sending all data to the backend. The interface that it uses is
```
export class NGXLogInterface {
  level: NgxLoggerLevel;
  timestamp: string;
  fileName: string;
  lineNumber: string;
  message: string;
  additional: any[];
}
```

the additional parameters should be a part of the "additional" field in the JSON object passed to the server. I hope this helps!

**Comment by stephanie-b1n3t** [comment]
Yes it definitely helps! Thanks a lot. \o/
