### ISSUE TITLE
[Feature] Throttle console/server logs?

### ISSUE THREAD

**Issue by antonellopasella** [dbfannin/ngx-logger#82]
Will be useful to have output throttled?
In my use case I have a lots of console.log and it's faster to have batched calls from a buffer instead of log each time

**Comment by appsolutegeek** [comment]
Yes, this would be really beneficial. RIght now, the server gets hit each time. Would be better to have a custom time that can be set so that it can buffer everything and then send them all at once every xx number of seconds.

**Comment by dbfannin** [comment]
@antonellopasella, @appsolutegeek, does #85 give you enough to serve your use case? You could disable the serverLogging int he logger, and register a custom log monitor, and handle the batch server logging yourself.

**Comment by antonellopasella** [comment]
I'll check! Thanks!

**Comment by antonellopasella** [comment]
It works perfectly

**Comment by appsolutegeek** [comment]
Sorry for the delay!

Yep, this works great - thanks

**Comment by atdiff** [comment]
@appsolutegeek or @antonellopasella, do you have examples of what you implemented for buffering the calls? I have a similar need, so rather than reinvent the wheel, thought I'd ask.
