### ISSUE TITLE
NGXLogger and unit tests

### ISSUE THREAD

**Issue by beleta** [dbfannin/ngx-logger#83]
NXLogger fails with this message: "zone.js:2990 Failed to load ng:///LoginModule/LoginComponent.ngfactory.js: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https." when used in an unit test. I know that there is NGXLoggerMock but I want to log messages when running my tests. 

If I can use console.log() in my tests why I cannot use logger.debug()?

**Comment by dbfannin** [comment]
@beleta, the logger does not currently support logging for tests when using the logger testing module. It's something that could pretty easily be added. If you'd like to take a stab at it, I'd be happy to look at the PR. Otherwise, it might be a while before someone else can pull in the work.

**Comment by beleta** [comment]
I don't know why, a new Angular version or some changes in this project, but is seems that the problem has disappeared.

**Comment by dbfannin** [comment]
Closing since this doesn't appear to be an issue anymore
