### ISSUE TITLE
Custom Log Monitor usage

### ISSUE THREAD

**Issue by mike131** [dbfannin/ngx-logger#89]
Currently have ngx logger in the the main app.module.ts

```
LoggerModule.forRoot({
      serverLoggingUrl: '/api/logs',
      level: NgxLoggerLevel.DEBUG,
      serverLogLevel: NgxLoggerLevel.ERROR
    }),
```

I see that custom log monitoring has been added, but im not quite sure how to add it to what we have already.

My end goal is to use a custom log monitor to log errors one place and debug to another place.

Any tips on how I can achieve this?

**Comment by dbfannin** [comment]
@mike131, did you get the answer you needed? Documentation for that has been added to New Features section (the top) of the readme. Please let me know if there are any ways that we can improve the documentation to make it more clear.

Thanks!
