### ISSUE TITLE
Send to web api still when console log is off

### ISSUE THREAD

**Issue by hakalb** [dbfannin/ngx-logger#9]
I would like to send to web api using the server log level filter even if console log level filer is off, or a higher log level than the server log level (ie console log errors and server log warnings).

My idea is that the two log level filters work independant of each other.
Would that be possible to implement?

**Comment by dbfannin** [comment]
@hakalb, This is something that would be pretty simple to implement. I will try to get on this sometime soon, or, if you would like, you can make the changes and send me a PR for them. If you're waiting on me, it might take a few days for me to get to it.

Thanks!

**Comment by dbfannin** [comment]
@hakalb, server logging when client logging disabled is now supported by the logger in version 0.2.5. You will need to supply serverLogLevel now in the config. you can set 

```
{
  serverLoggingUrl: '/api/logs', 
  level: NgxLoggerLevel.OFF, 
  serverLogLevel: NgxLoggerLevel.WARN
}
```

which will disable logging for the client, but log Warn+ on the server.
