### ISSUE TITLE
Fix NPM warning for Angular 7 support

### ISSUE THREAD

**Issue by kathomas921** [dbfannin/ngx-logger#90]
After upgrading to Angular 7.0.0, running `npm install` yields
`npm WARN ngx-logger@3.3.3 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-logger@3.3.3 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.`

Please update the package.json to allow for Angular 7.x in addition to 6.0.0.

**Comment by samfrach** [comment]
I have the same need please

**Comment by dbfannin** [comment]
@kathomas921, @samfrach I believe ngx-logger@3.3.4 should fix those warns!
