### ISSUE TITLE
demo app fails to compile

### ISSUE THREAD

**Issue by marclabud** [dbfannin/ngx-logger#93]
run
`ng serve demo`

leads to the following error messages:

ERROR in node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts(8,106): error TS2307: Cannot find module '@angular/animations'.
node_modules/@angular/platform-browser/animations/src/animation_renderer.d.ts(1,53): error TS2307: Cannot find module '@angular/animations/browser'.
node_modules/@angular/platform-browser/animations/src/providers.d.ts(8,276): error TS2307: Cannot find module '@angular/animations/browser'.
projects/demo/src/app/app.module.ts(4,37): error TS2307: Cannot find module '@angular/forms'.
projects/demo/src/app/app.module.ts(13,8): error TS2307: Cannot find module '@angular/material'.
projects/demo/src/app/logger-form/logger-form.component.ts(7,8): error TS2307: Cannot find module '@angular/forms'.

The missing modules where removed with commit  'remove unnecessary angular packages'.

**Comment by marclabud** [comment]
Workaround: Install peer dependencies manual:
for angular 6

    "peerDependencies": {
    "@angular/common": "^6.0.0 || ^7.0.0",
    "@angular/core": "^6.0.0 || ^7.0.0"
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^6.4.7",
    "@angular/forms": "^6.1.10",
    "@angular/material": "^6.4.7",
    "rxjs": "^6.0.0"
     }

**Comment by saidoze** [comment]
That workaround doesn't do the trick with me.

After removing the line "@import '~@angular/material/prebuilt-themes/indigo-pink.css';" in styles.scss, i get the following remaining errors:

ERROR in node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts(8,106): error TS2307: Cannot find module '@angular/animations'.
node_modules/@angular/platform-browser/animations/src/animation_renderer.d.ts(1,53): error TS2307: Cannot find module '@angular/animations/browser'.
node_modules/@angular/platform-browser/animations/src/providers.d.ts(8,276): error TS2307: Cannot find module '@angular/animations/browser'.
projects/demo/src/app/app.module.ts(4,37): error TS2307: Cannot find module '@angular/forms'.
projects/demo/src/app/app.module.ts(13,8): error TS2307: Cannot find module '@angular/material'.
projects/demo/src/app/logger-form/logger-form.component.ts(7,8): error TS2307: Cannot find module '@angular/forms'.

when doing a ng serve demo

**Comment by dbfannin** [comment]
Yikes. Thanks for catching this. I hadn't tried to run the demo before. Seemed like a low risk change. Looks like we were missing some devDependencies. I've updated the devDependencies. Please pull down latest master and see if the demo app loads for you now.

**Comment by marclabud** [comment]
Thank you for the fast update of the devDependencies of the demo app. It is back to work now.

**Comment by marclabud** [comment]
@saidoze: Have you installed the peer dependencies manual with

    npm i @angular/animations@6.1.10 @angular/cdk@6.4.7 @angular/forms@6.1.10 @angular/material@6.4.7

?
But this is history due to the fast demo fix.

**Comment by dbfannin** [comment]
There should be no need to manually install any dependencies.

**Comment by marclabud** [comment]
No there is no need to manually install any dependencies with your solution with devDependencies.
I just answered to the question of @saidoze with my peerDependency-Workaround.
