### ISSUE TITLE
Custom logger and console.log output

### ISSUE THREAD

**Issue by appsolutegeek** [dbfannin/ngx-logger#95]
Hi,

I have implemented a custom logger and it arrives there. I wanted to do all my logging in my custom logger because i dont want any output to the console. Right now i am seeing..

```
ngx-logger.js:228 2018-10-31T14:18:45.675Z ERROR [main.js:4864] THIS WAS ERROR

2018-10-31T14:18:51.650Z INFO [main.js:4866] THIS WAS INFO
```

ngx-logger is logging to the console, is it possible to turn this off ?

I have my  custom logger

```
import { NGXLoggerMonitor, NGXLogInterface, Levels } from "ngx-logger"

export class MyLoggerMonitor implements NGXLoggerMonitor {
  onLog(log: NGXLogInterface) {
    debugger
    //console.log("myCustomLoggerMonitor", log)
  }
}
```

and my main logger service, where I inject NGXlogger

```
  constructor(private logger: NGXLogger) {

    this.logger.registerMonitor(new MyLoggerMonitor())

    this.logger.updateConfig({ level: NgxLoggerLevel.INFO })

    this.logger.error("THIS WAS ERROR")
    this.logger.debug("THIS WAS DEBUG")
    this.logger.info("THIS WAS INFO")
```

I basically have wrapping methods ie..

```
  debug(message: string, ...additional: any[]) {
    this.logger.debug(message, additional)
  }

  info(message: string, ...additional: any[]) {
    this.logger.info(message, additional)
  }
```

and I set this up in my core module -imports,  like so

```
    LoggerModule.forRoot({ level: NgxLoggerLevel.OFF })
```

As I say, it does work, it arrives inside my custom logger when I do a logger.info for example BUT the it still does a console.log

Can this be turned off in production, I can't set the log level to OFF as then my custom logger doesn't get activated.

Any ideas - thanks in advance

**Comment by dbfannin** [comment]
@appsolutegeek, I've added support for this. To disable console logging, there is a new config option in ngx-logger@3.3.6 = `disableConsoleLogging`. Set this to true, and it will disable the browser's logging, but still alert your custom logger. I hope this helps!

**Comment by appsolutegeek** [comment]
Yes, it will! Great stuff - thanks, I will download it a.s.a.p. and give it a go.

Thanks for the rapid response!

**Comment by appsolutegeek** [comment]
hi @dbfannin , I finally got around to try this.

It does seems to work but a small issue - although I worked around it

I have the following line to update the level - in code

```
    this.logger.updateConfig({ level: NgxLoggerLevel.INFO })
```

but setting this seems to cause a problem and the console logs are actually re-enabled.

I have to do the following

```
    this.logger.updateConfig({ level: NgxLoggerLevel.INFO, disableConsoleLogging: true })
```

To confirm, I have this set

```
    LoggerModule.forRoot({ level: NgxLoggerLevel.OFF, disableConsoleLogging: true })
```

Anyway, I have worked around it., but thought I would report it 

Thanks in advance

**Comment by dbfannin** [comment]
@appsolutegeek, this is by design. Updated the config is meant to completely overwrite the current config. We want to be explicit. There would be ambiguity if we were to just extend the config.

We do provide a method called `getConfigSnapshot()`, so if you wanted to update a single value, you could just

```
const config = this.logger.getConfigSnapshot();
config.level = NgxLoggerLevel.INFO;
this.logger.updateConfig(config);
```

**Comment by appsolutegeek** [comment]
great, that works for me. Thanks
