### ISSUE TITLE
Not possible to log empty messages

### ISSUE THREAD

**Issue by lppedd** [dbfannin/ngx-logger#97]
Trying to log something like:

```
const message = ''
logger.debug(message)
```
output nothing, as I noticed you do this check:

https://github.com/dbfannin/ngx-logger/blob/72b548e16d689835817ef01e03b0c8cad8326623/src/lib/logger.service.ts#L148

Logging empty values may be important too. What do you think?

**Comment by dbfannin** [comment]
@lppedd, Can you help me understand the use case for logging empty message? I'm just not sure I understand how this would be helpful.

**Comment by lppedd** [comment]
@dbfannin E.g. I was debug logging my search component's input field and when clearing the field I saw nothing was printed out in the console. First thing I tought was clearing the input was not really working, while it was, infact, it was just ngx-logger not logging an empty message.

**Comment by dbfannin** [comment]
Hmm. It is usually best practice to include a message with a variable. If a variable string was stored in logs, it could be difficult to figure out the context of the that log. In the scenario you described, the logger should be called like:  `this.logger.debug('MyVariableName', this.myVariableName);` 

I don't think there is enough pull for this from the community to make this change. In fact, it may cause more empty logs to show up in user's log files and them not understand why. For now, we will leave as is, unless more people request this change.

Thanks!

**Comment by Mat2095** [comment]
I disagree, filtering out empty messages is an unexpected behaviour and causes confusion.

Also, it only checks the first argument.
In my scenario, I'm using two arguments, the first is an optional "prefix". If it is empty, the message isn't logged, although the second argument is not empty.
