### ISSUE TITLE
Feature request - disable client log and enable logging via custom log monitor

### ISSUE THREAD

**Issue by NithinBiliya** [dbfannin/ngx-logger#98]
Use case - 
No logs to be written into browser console, all logs to be written to a web-service with custom log object structure. 

Implemented logging to server using log monitor. Now I need to enable log monitor but disable client logging. But currently if I disable client logging, the log monitor itself is disable (and subsequently the server logging is disabled).

**Comment by NithinBiliya** [comment]
also currently not able to set the client logging to higher level and server logging (implemented via log monitor) to higher level

**Comment by dbfannin** [comment]
@NithinBiliya, You can disable console logs using the config flag `disableConsoleLogging: true`. The server log level is not meant to control the log monitor level. It is only meant to control the built in server logging. You will need to set the `level` value to the log level you wish for your custom logger and `disableConsoleLogging: true` and you will get the desired effect.

**Comment by NithinBiliya** [comment]
disableConsoleLogging: true is what I was looking for. Thanks for the quick reply.
